// @generated by protoc-gen-es v2.14.1 with parameter "target=ts"
// @generated from file bilibili/vega/deneb/v1/deneb.proto (package bilibili.vega.deneb.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Any } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_any } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file bilibili/vega/deneb/v1/deneb.proto.
 */
export const file_bilibili_vega_deneb_v1_deneb: GenFile = /*@__PURE__*/
  fileDesc("CiJiaWxpYmlsaS92ZWdhL2RlbmViL3YxL2RlbmViLnByb3RvEhZiaWxpYmlsaS52ZWdhLmRlbmViLnYxInAKEU1lc3NhZ2VQdWxsc1JlcGx5EiIKBGRhdGEYASADKAsyFC5nb29nbGUucHJvdG9idWYuQW55EgoKAnBuGAIgASgFEgoKAnBzGAMgASgFEg0KBWNvdW50GAQgASgDEhAKCGhhc19uZXh0GAUgASgIIlMKD01lc3NhZ2VQdWxsc1JlcRIUCgxzdGFydF9zZXFfaWQYASABKAMSEgoKZW5kX3NlcV9pZBgCIAEoAxIKCgJwbhgDIAEoBRIKCgJwcxgEIAEoBTJyCgxWZWdhRGVuZWJSUEMSYgoMTWVzc2FnZVB1bGxzEicuYmlsaWJpbGkudmVnYS5kZW5lYi52MS5NZXNzYWdlUHVsbHNSZXEaKS5iaWxpYmlsaS52ZWdhLmRlbmViLnYxLk1lc3NhZ2VQdWxsc1JlcGx5YgZwcm90bzM", [file_google_protobuf_any]);

/**
 * @generated from message bilibili.vega.deneb.v1.MessagePullsReply
 */
export type MessagePullsReply = Message<"bilibili.vega.deneb.v1.MessagePullsReply"> & {
  /**
   * @generated from field: repeated google.protobuf.Any data = 1;
   */
  data: Any[];

  /**
   * @generated from field: int32 pn = 2;
   */
  pn: number;

  /**
   * @generated from field: int32 ps = 3;
   */
  ps: number;

  /**
   * @generated from field: int64 count = 4;
   */
  count: bigint;

  /**
   * @generated from field: bool has_next = 5;
   */
  hasNext: boolean;
};

/**
 * Describes the message bilibili.vega.deneb.v1.MessagePullsReply.
 * Use `create(MessagePullsReplySchema)` to create a new message.
 */
export const MessagePullsReplySchema: GenMessage<MessagePullsReply> = /*@__PURE__*/
  messageDesc(file_bilibili_vega_deneb_v1_deneb, 0);

/**
 * @generated from message bilibili.vega.deneb.v1.MessagePullsReq
 */
export type MessagePullsReq = Message<"bilibili.vega.deneb.v1.MessagePullsReq"> & {
  /**
   * @generated from field: int64 start_seq_id = 1;
   */
  startSeqId: bigint;

  /**
   * @generated from field: int64 end_seq_id = 2;
   */
  endSeqId: bigint;

  /**
   * @generated from field: int32 pn = 3;
   */
  pn: number;

  /**
   * @generated from field: int32 ps = 4;
   */
  ps: number;
};

/**
 * Describes the message bilibili.vega.deneb.v1.MessagePullsReq.
 * Use `create(MessagePullsReqSchema)` to create a new message.
 */
export const MessagePullsReqSchema: GenMessage<MessagePullsReq> = /*@__PURE__*/
  messageDesc(file_bilibili_vega_deneb_v1_deneb, 1);

/**
 * @generated from service bilibili.vega.deneb.v1.VegaDenebRPC
 */
export const VegaDenebRPC: GenService<{
  /**
   * @generated from rpc bilibili.vega.deneb.v1.VegaDenebRPC.MessagePulls
   */
  messagePulls: {
    methodKind: "unary";
    input: typeof MessagePullsReqSchema;
    output: typeof MessagePullsReplySchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_bilibili_vega_deneb_v1_deneb, 0);

