// @generated by protoc-gen-es v2.14.1 with parameter "target=ts"
// @generated from file bilibili/live/general/interfaces/v1/interfaces.proto (package bilibili.live.general.interfaces.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file bilibili/live/general/interfaces/v1/interfaces.proto.
 */
export const file_bilibili_live_general_interfaces_v1_interfaces: GenFile = /*@__PURE__*/
  fileDesc("CjRiaWxpYmlsaS9saXZlL2dlbmVyYWwvaW50ZXJmYWNlcy92MS9pbnRlcmZhY2VzLnByb3RvEiNiaWxpYmlsaS5saXZlLmdlbmVyYWwuaW50ZXJmYWNlcy52MSJkChBHZXRPbmxpbmVSYW5rUmVxEgwKBHJ1aWQYASABKAMSDwoHcm9vbV9pZBgCIAEoAxIMCgRwYWdlGAMgASgDEhEKCXBhZ2Vfc2l6ZRgEIAEoAxIQCghwbGF0Zm9ybRgFIAEoCSKqAgoRR2V0T25saW5lUmFua1Jlc3ASUwoEaXRlbRgBIAEoCzJFLmJpbGliaWxpLmxpdmUuZ2VuZXJhbC5pbnRlcmZhY2VzLnYxLkdldE9ubGluZVJhbmtSZXNwLk9ubGluZVJhbmtJdGVtEhIKCm9ubGluZV9udW0YAiABKAMaqwEKDk9ubGluZVJhbmtJdGVtEgsKA3VpZBgBIAEoAxINCgV1bmFtZRgCIAEoCRIMCgRmYWNlGAMgASgJEhYKDmNvbnRpbnVlX3dhdGNoGAQgASgDEkIKCm1lZGFsX2luZm8YBSABKAsyLi5iaWxpYmlsaS5saXZlLmdlbmVyYWwuaW50ZXJmYWNlcy52MS5NZWRhbEluZm8SEwoLZ3VhcmRfbGV2ZWwYBiABKAMiuAEKCU1lZGFsSW5mbxITCgtndWFyZF9sZXZlbBgBIAEoAxIZChFtZWRhbF9jb2xvcl9zdGFydBgCIAEoAxIXCg9tZWRhbF9jb2xvcl9lbmQYAyABKAMSGgoSbWVkYWxfY29sb3JfYm9yZGVyGAQgASgDEhIKCm1lZGFsX25hbWUYBSABKAkSDQoFbGV2ZWwYBiABKAMSEQoJdGFyZ2V0X2lkGAcgASgDEhAKCGlzX2xpZ2h0GAggASgDYgZwcm90bzM");

/**
 * @generated from message bilibili.live.general.interfaces.v1.GetOnlineRankReq
 */
export type GetOnlineRankReq = Message<"bilibili.live.general.interfaces.v1.GetOnlineRankReq"> & {
  /**
   * @generated from field: int64 ruid = 1;
   */
  ruid: bigint;

  /**
   * @generated from field: int64 room_id = 2;
   */
  roomId: bigint;

  /**
   * @generated from field: int64 page = 3;
   */
  page: bigint;

  /**
   * @generated from field: int64 page_size = 4;
   */
  pageSize: bigint;

  /**
   * @generated from field: string platform = 5;
   */
  platform: string;
};

/**
 * Describes the message bilibili.live.general.interfaces.v1.GetOnlineRankReq.
 * Use `create(GetOnlineRankReqSchema)` to create a new message.
 */
export const GetOnlineRankReqSchema: GenMessage<GetOnlineRankReq> = /*@__PURE__*/
  messageDesc(file_bilibili_live_general_interfaces_v1_interfaces, 0);

/**
 * @generated from message bilibili.live.general.interfaces.v1.GetOnlineRankResp
 */
export type GetOnlineRankResp = Message<"bilibili.live.general.interfaces.v1.GetOnlineRankResp"> & {
  /**
   * @generated from field: bilibili.live.general.interfaces.v1.GetOnlineRankResp.OnlineRankItem item = 1;
   */
  item?: GetOnlineRankResp_OnlineRankItem | undefined;

  /**
   * @generated from field: int64 online_num = 2;
   */
  onlineNum: bigint;
};

/**
 * Describes the message bilibili.live.general.interfaces.v1.GetOnlineRankResp.
 * Use `create(GetOnlineRankRespSchema)` to create a new message.
 */
export const GetOnlineRankRespSchema: GenMessage<GetOnlineRankResp> = /*@__PURE__*/
  messageDesc(file_bilibili_live_general_interfaces_v1_interfaces, 1);

/**
 * @generated from message bilibili.live.general.interfaces.v1.GetOnlineRankResp.OnlineRankItem
 */
export type GetOnlineRankResp_OnlineRankItem = Message<"bilibili.live.general.interfaces.v1.GetOnlineRankResp.OnlineRankItem"> & {
  /**
   * @generated from field: int64 uid = 1;
   */
  uid: bigint;

  /**
   * @generated from field: string uname = 2;
   */
  uname: string;

  /**
   * @generated from field: string face = 3;
   */
  face: string;

  /**
   * @generated from field: int64 continue_watch = 4;
   */
  continueWatch: bigint;

  /**
   * @generated from field: bilibili.live.general.interfaces.v1.MedalInfo medal_info = 5;
   */
  medalInfo?: MedalInfo | undefined;

  /**
   * @generated from field: int64 guard_level = 6;
   */
  guardLevel: bigint;
};

/**
 * Describes the message bilibili.live.general.interfaces.v1.GetOnlineRankResp.OnlineRankItem.
 * Use `create(GetOnlineRankResp_OnlineRankItemSchema)` to create a new message.
 */
export const GetOnlineRankResp_OnlineRankItemSchema: GenMessage<GetOnlineRankResp_OnlineRankItem> = /*@__PURE__*/
  messageDesc(file_bilibili_live_general_interfaces_v1_interfaces, 1, 0);

/**
 * @generated from message bilibili.live.general.interfaces.v1.MedalInfo
 */
export type MedalInfo = Message<"bilibili.live.general.interfaces.v1.MedalInfo"> & {
  /**
   * @generated from field: int64 guard_level = 1;
   */
  guardLevel: bigint;

  /**
   * @generated from field: int64 medal_color_start = 2;
   */
  medalColorStart: bigint;

  /**
   * @generated from field: int64 medal_color_end = 3;
   */
  medalColorEnd: bigint;

  /**
   * @generated from field: int64 medal_color_border = 4;
   */
  medalColorBorder: bigint;

  /**
   * @generated from field: string medal_name = 5;
   */
  medalName: string;

  /**
   * @generated from field: int64 level = 6;
   */
  level: bigint;

  /**
   * @generated from field: int64 target_id = 7;
   */
  targetId: bigint;

  /**
   * @generated from field: int64 is_light = 8;
   */
  isLight: bigint;
};

/**
 * Describes the message bilibili.live.general.interfaces.v1.MedalInfo.
 * Use `create(MedalInfoSchema)` to create a new message.
 */
export const MedalInfoSchema: GenMessage<MedalInfo> = /*@__PURE__*/
  messageDesc(file_bilibili_live_general_interfaces_v1_interfaces, 2);

