// @generated by protoc-gen-es v2.14.1 with parameter "target=ts"
// @generated from file bilibili/broadcast/message/fission/notify.proto (package bilibili.broadcast.message.fission, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { EmptySchema } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_empty } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file bilibili/broadcast/message/fission/notify.proto.
 */
export const file_bilibili_broadcast_message_fission_notify: GenFile = /*@__PURE__*/
  fileDesc("Ci9iaWxpYmlsaS9icm9hZGNhc3QvbWVzc2FnZS9maXNzaW9uL25vdGlmeS5wcm90bxIiYmlsaWJpbGkuYnJvYWRjYXN0Lm1lc3NhZ2UuZmlzc2lvbiItCg9HYW1lTm90aWZ5UmVwbHkSDAoEdHlwZRgBIAEoDRIMCgRkYXRhGAIgASgJMmYKB0Zpc3Npb24SWwoKR2FtZU5vdGlmeRIWLmdvb2dsZS5wcm90b2J1Zi5FbXB0eRozLmJpbGliaWxpLmJyb2FkY2FzdC5tZXNzYWdlLmZpc3Npb24uR2FtZU5vdGlmeVJlcGx5MAFiBnByb3RvMw", [file_google_protobuf_empty]);

/**
 * @generated from message bilibili.broadcast.message.fission.GameNotifyReply
 */
export type GameNotifyReply = Message<"bilibili.broadcast.message.fission.GameNotifyReply"> & {
  /**
   * 类型字段
   *
   * @generated from field: uint32 type = 1;
   */
  type: number;

  /**
   * 数据字段
   *
   * @generated from field: string data = 2;
   */
  data: string;
};

/**
 * Describes the message bilibili.broadcast.message.fission.GameNotifyReply.
 * Use `create(GameNotifyReplySchema)` to create a new message.
 */
export const GameNotifyReplySchema: GenMessage<GameNotifyReply> = /*@__PURE__*/
  messageDesc(file_bilibili_broadcast_message_fission_notify, 0);

/**
 * @generated from service bilibili.broadcast.message.fission.Fission
 */
export const Fission: GenService<{
  /**
   * @generated from rpc bilibili.broadcast.message.fission.Fission.GameNotify
   */
  gameNotify: {
    methodKind: "server_streaming";
    input: typeof EmptySchema;
    output: typeof GameNotifyReplySchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_bilibili_broadcast_message_fission_notify, 0);

