name: Composite React Native Setup
description: setup everything react native needs (node, secret, etc)

inputs:
  env:
    description: "env file content"
    required: true
  sentry:
    description: "sentry file content"
    required: true

runs:
  using: "composite"
  steps:
    - name: Get branch name
      run: |
        # Short name for current branch. For PRs, use target branch (base ref)
        GIT_BRANCH=${GITHUB_BASE_REF:-${GITHUB_REF#refs/heads/}}
        echo "GIT_BRANCH=$GIT_BRANCH" >> $GITHUB_ENV
      shell: bash

    - name: Get current date
      id: date
      run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
      shell: bash

    - name: enable corepack
      run: corepack enable
      shell: bash

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'yarn'

    - name: 'Create env file'
      env:
        ENV_FILE: ${{ inputs.env }}
        SENTRY_PROPERTIES: ${{ inputs.sentry }}
      run: |
        echo "$ENV_FILE" > .env
        echo "$SENTRY_PROPERTIES" > ./android/sentry.properties
        echo "$SENTRY_PROPERTIES" > ./ios/sentry.properties
      shell: bash
      
    - name: alias yarn.cmd to yarn
      run: alias yarn.cmd="yarn"
      shell: bash

    - name: Install dependencies
      run: yarn install; yarn build
      shell: bash

    - name: python fixHTTP
      run: |
        python ./scripts/fixHTTP.py
      shell: bash
