// @generated by protoc-gen-es v2.14.1 with parameter "target=ts"
// @generated from file bilibili/broadcast/v1/laser.proto (package bilibili.broadcast.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { EmptySchema } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_empty } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file bilibili/broadcast/v1/laser.proto.
 */
export const file_bilibili_broadcast_v1_laser: GenFile = /*@__PURE__*/
  fileDesc("CiFiaWxpYmlsaS9icm9hZGNhc3QvdjEvbGFzZXIucHJvdG8SFWJpbGliaWxpLmJyb2FkY2FzdC52MSIyChJMYXNlckxvZ1VwbG9hZFJlc3ASDgoGdGFza2lkGAEgASgDEgwKBGRhdGUYAiABKAkyYwoFTGFzZXISWgoTV2F0Y2hMb2dVcGxvYWRFdmVudBIWLmdvb2dsZS5wcm90b2J1Zi5FbXB0eRopLmJpbGliaWxpLmJyb2FkY2FzdC52MS5MYXNlckxvZ1VwbG9hZFJlc3AwAWIGcHJvdG8z", [file_google_protobuf_empty]);

/**
 * 服务端下发日志上报事件
 *
 * @generated from message bilibili.broadcast.v1.LaserLogUploadResp
 */
export type LaserLogUploadResp = Message<"bilibili.broadcast.v1.LaserLogUploadResp"> & {
  /**
   * 任务id
   *
   * @generated from field: int64 taskid = 1;
   */
  taskid: bigint;

  /**
   * 下发时间
   *
   * @generated from field: string date = 2;
   */
  date: string;
};

/**
 * Describes the message bilibili.broadcast.v1.LaserLogUploadResp.
 * Use `create(LaserLogUploadRespSchema)` to create a new message.
 */
export const LaserLogUploadRespSchema: GenMessage<LaserLogUploadResp> = /*@__PURE__*/
  messageDesc(file_bilibili_broadcast_v1_laser, 0);

/**
 * Laser
 *
 * @generated from service bilibili.broadcast.v1.Laser
 */
export const Laser: GenService<{
  /**
   * 监听上报事件
   *
   * @generated from rpc bilibili.broadcast.v1.Laser.WatchLogUploadEvent
   */
  watchLogUploadEvent: {
    methodKind: "server_streaming";
    input: typeof EmptySchema;
    output: typeof LaserLogUploadRespSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_bilibili_broadcast_v1_laser, 0);

