// @generated by protoc-gen-es v2.14.1 with parameter "target=ts"
// @generated from file bilibili/broadcast/v1/mod.proto (package bilibili.broadcast.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { EmptySchema } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_empty } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file bilibili/broadcast/v1/mod.proto.
 */
export const file_bilibili_broadcast_v1_mod: GenFile = /*@__PURE__*/
  fileDesc("Ch9iaWxpYmlsaS9icm9hZGNhc3QvdjEvbW9kLnByb3RvEhViaWxpYmlsaS5icm9hZGNhc3QudjEiiAEKD01vZFJlc291cmNlUmVzcBIOCgZhdGNpb24YASABKAUSDwoHYXBwX2tleRgCIAEoCRIRCglwb29sX25hbWUYAyABKAkSEwoLbW9kdWxlX25hbWUYBCABKAkSFgoObW9kdWxlX3ZlcnNpb24YBSABKAMSFAoMbGlzdF92ZXJzaW9uGAYgASgDMl8KCk1vZE1hbmFnZXISUQoNV2F0Y2hSZXNvdXJjZRIWLmdvb2dsZS5wcm90b2J1Zi5FbXB0eRomLmJpbGliaWxpLmJyb2FkY2FzdC52MS5Nb2RSZXNvdXJjZVJlc3AwAWIGcHJvdG8z", [file_google_protobuf_empty]);

/**
 * @generated from message bilibili.broadcast.v1.ModResourceResp
 */
export type ModResourceResp = Message<"bilibili.broadcast.v1.ModResourceResp"> & {
  /**
   * @generated from field: int32 atcion = 1;
   */
  atcion: number;

  /**
   * @generated from field: string app_key = 2;
   */
  appKey: string;

  /**
   * @generated from field: string pool_name = 3;
   */
  poolName: string;

  /**
   * @generated from field: string module_name = 4;
   */
  moduleName: string;

  /**
   * @generated from field: int64 module_version = 5;
   */
  moduleVersion: bigint;

  /**
   * @generated from field: int64 list_version = 6;
   */
  listVersion: bigint;
};

/**
 * Describes the message bilibili.broadcast.v1.ModResourceResp.
 * Use `create(ModResourceRespSchema)` to create a new message.
 */
export const ModResourceRespSchema: GenMessage<ModResourceResp> = /*@__PURE__*/
  messageDesc(file_bilibili_broadcast_v1_mod, 0);

/**
 * ModManager
 *
 * @generated from service bilibili.broadcast.v1.ModManager
 */
export const ModManager: GenService<{
  /**
   * @generated from rpc bilibili.broadcast.v1.ModManager.WatchResource
   */
  watchResource: {
    methodKind: "server_streaming";
    input: typeof EmptySchema;
    output: typeof ModResourceRespSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_bilibili_broadcast_v1_mod, 0);

