// @generated by protoc-gen-es v2.14.1 with parameter "target=ts"
// @generated from file bilibili/broadcast/v1/push.proto (package bilibili.broadcast.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { EmptySchema } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_empty } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file bilibili/broadcast/v1/push.proto.
 */
export const file_bilibili_broadcast_v1_push: GenFile = /*@__PURE__*/
  fileDesc("CiBiaWxpYmlsaS9icm9hZGNhc3QvdjEvcHVzaC5wcm90bxIVYmlsaWJpbGkuYnJvYWRjYXN0LnYxIhsKDVBhZ2VCbGFja0xpc3QSCgoCaWQYASABKAkiFgoIUGFnZVZpZXcSCgoCaWQYASABKAkinQYKD1B1c2hNZXNzYWdlUmVzcBISCgpvbGRfdGFza2lkGAEgASgDEjcKA2JpehgCIAEoDjIqLmJpbGliaWxpLmJyb2FkY2FzdC52MS5QdXNoTWVzc2FnZVJlc3AuQml6EjkKBHR5cGUYAyABKA4yKy5iaWxpYmlsaS5icm9hZGNhc3QudjEuUHVzaE1lc3NhZ2VSZXNwLlR5cGUSDQoFdGl0bGUYBCABKAkSDwoHc3VtbWFyeRgFIAEoCRILCgNpbWcYBiABKAkSDAoEbGluaxgHIAEoCRJBCghwb3NpdGlvbhgIIAEoDjIvLmJpbGliaWxpLmJyb2FkY2FzdC52MS5QdXNoTWVzc2FnZVJlc3AuUG9zaXRpb24SEAoIZHVyYXRpb24YCSABKAUSDgoGZXhwaXJlGAogASgDEg4KBnRhc2tpZBgLIAEoCRI8Cg5wYWdlX2JsYWNrTGlzdBgMIAMoCzIkLmJpbGliaWxpLmJyb2FkY2FzdC52MS5QYWdlQmxhY2tMaXN0EjIKCXBhZ2VfdmlldxgNIAMoCzIfLmJpbGliaWxpLmJyb2FkY2FzdC52MS5QYWdlVmlldxI+Cg90YXJnZXRfcmVzb3VyY2UYDiABKAsyJS5iaWxpYmlsaS5icm9hZGNhc3QudjEuVGFyZ2V0UmVzb3VyY2USEwoLaW1hZ2VfZnJhbWUYDyABKAUSFAoMaW1hZ2VfbWFya2VyGBAgASgFEhYKDmltYWdlX3Bvc2l0aW9uGBEgASgFEgsKA2pvYhgSIAEoAyJFCgNCaXoSDwoLQklaX1VOS05PV04QABINCglCSVpfVklERU8QARIMCghCSVpfTElWRRACEhAKDEJJWl9BQ1RJVklUWRADIl8KBFR5cGUSEAoMVFlQRV9VTktOT1dOEAASEAoMVFlQRV9ERUZBVUxUEAESDAoIVFlQRV9IT1QQAhIRCg1UWVBFX1JFQUxUSU1FEAMSEgoOVFlQRV9SRUNPTU1FTkQQBCIoCghQb3NpdGlvbhIPCgtQT1NfVU5LTk9XThAAEgsKB1BPU19UT1AQASK3AQoOVGFyZ2V0UmVzb3VyY2USLQoEVHlwZRgBIAEoDjIfLmJpbGliaWxpLmJyb2FkY2FzdC52MS5MaW5rVHlwZRJFCghSZXNvdXJjZRgCIAMoCzIzLmJpbGliaWxpLmJyb2FkY2FzdC52MS5UYXJnZXRSZXNvdXJjZS5SZXNvdXJjZUVudHJ5Gi8KDVJlc291cmNlRW50cnkSCwoDa2V5GAEgASgJEg0KBXZhbHVlGAIgASgJOgI4ASphCghMaW5rVHlwZRIVChFMSU5LX1RZUEVfVU5LTk9XThAAEhUKEUxJTktfVFlQRV9CQU5HVU1JEAESEwoPTElOS19UWVBFX1ZJREVPEAISEgoOTElOS19UWVBFX0xJVkUQAzJYCgRQdXNoElAKDFdhdGNoTWVzc2FnZRIWLmdvb2dsZS5wcm90b2J1Zi5FbXB0eRomLmJpbGliaWxpLmJyb2FkY2FzdC52MS5QdXNoTWVzc2FnZVJlc3AwAWIGcHJvdG8z", [file_google_protobuf_empty]);

/**
 * @generated from message bilibili.broadcast.v1.PageBlackList
 */
export type PageBlackList = Message<"bilibili.broadcast.v1.PageBlackList"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message bilibili.broadcast.v1.PageBlackList.
 * Use `create(PageBlackListSchema)` to create a new message.
 */
export const PageBlackListSchema: GenMessage<PageBlackList> = /*@__PURE__*/
  messageDesc(file_bilibili_broadcast_v1_push, 0);

/**
 * @generated from message bilibili.broadcast.v1.PageView
 */
export type PageView = Message<"bilibili.broadcast.v1.PageView"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message bilibili.broadcast.v1.PageView.
 * Use `create(PageViewSchema)` to create a new message.
 */
export const PageViewSchema: GenMessage<PageView> = /*@__PURE__*/
  messageDesc(file_bilibili_broadcast_v1_push, 1);

/**
 * @generated from message bilibili.broadcast.v1.PushMessageResp
 */
export type PushMessageResp = Message<"bilibili.broadcast.v1.PushMessageResp"> & {
  /**
   * Deprecated: 推送任务id，使用string
   *
   * @generated from field: int64 old_taskid = 1;
   */
  oldTaskid: bigint;

  /**
   * 业务
   * 1:是视频 2:是直播 3:是活动
   *
   * @generated from field: bilibili.broadcast.v1.PushMessageResp.Biz biz = 2;
   */
  biz: PushMessageResp_Biz;

  /**
   * 类型
   * 1:是默认 2:是热门 3:是实时 4:是推荐
   *
   * @generated from field: bilibili.broadcast.v1.PushMessageResp.Type type = 3;
   */
  type: PushMessageResp_Type;

  /**
   * 主标题
   *
   * @generated from field: string title = 4;
   */
  title: string;

  /**
   * 副标题
   *
   * @generated from field: string summary = 5;
   */
  summary: string;

  /**
   * 图片地址
   *
   * @generated from field: string img = 6;
   */
  img: string;

  /**
   * 跳转地址
   *
   * @generated from field: string link = 7;
   */
  link: string;

  /**
   * 展示位置，1是顶部
   *
   * @generated from field: bilibili.broadcast.v1.PushMessageResp.Position position = 8;
   */
  position: PushMessageResp_Position;

  /**
   * 展示时长（单位：秒），默认3秒
   *
   * @generated from field: int32 duration = 9;
   */
  duration: number;

  /**
   * 失效时间
   *
   * @generated from field: int64 expire = 10;
   */
  expire: bigint;

  /**
   * 推送任务id
   *
   * @generated from field: string taskid = 11;
   */
  taskid: string;

  /**
   * 应用内推送黑名单
   * UGC:     ugc-video-detail
   * PGC:     pgc-video-detail
   * 一起看:   pgc-video-detail-theater
   * 直播:     live-room-detail
   * Story:    ugc-video-detail-vertical
   * 播单黑名单 playlist-video-detail
   *
   * @generated from field: repeated bilibili.broadcast.v1.PageBlackList page_blackList = 12;
   */
  pageBlackList: PageBlackList[];

  /**
   * 预留pvid
   *
   * @generated from field: repeated bilibili.broadcast.v1.PageView page_view = 13;
   */
  pageView: PageView[];

  /**
   * 跳转资源
   *
   * @generated from field: bilibili.broadcast.v1.TargetResource target_resource = 14;
   */
  targetResource?: TargetResource | undefined;

  /**
   * @generated from field: int32 image_frame = 15;
   */
  imageFrame: number;

  /**
   * @generated from field: int32 image_marker = 16;
   */
  imageMarker: number;

  /**
   * @generated from field: int32 image_position = 17;
   */
  imagePosition: number;

  /**
   * @generated from field: int64 job = 18;
   */
  job: bigint;
};

/**
 * Describes the message bilibili.broadcast.v1.PushMessageResp.
 * Use `create(PushMessageRespSchema)` to create a new message.
 */
export const PushMessageRespSchema: GenMessage<PushMessageResp> = /*@__PURE__*/
  messageDesc(file_bilibili_broadcast_v1_push, 2);

/**
 * 业务类型
 *
 * @generated from enum bilibili.broadcast.v1.PushMessageResp.Biz
 */
export enum PushMessageResp_Biz {
  /**
   * 未知
   *
   * @generated from enum value: BIZ_UNKNOWN = 0;
   */
  UNKNOWN = 0,

  /**
   * 视频
   *
   * @generated from enum value: BIZ_VIDEO = 1;
   */
  VIDEO = 1,

  /**
   * 直播
   *
   * @generated from enum value: BIZ_LIVE = 2;
   */
  LIVE = 2,

  /**
   * 活动
   *
   * @generated from enum value: BIZ_ACTIVITY = 3;
   */
  ACTIVITY = 3,
}

/**
 * Describes the enum bilibili.broadcast.v1.PushMessageResp.Biz.
 */
export const PushMessageResp_BizSchema: GenEnum<PushMessageResp_Biz> = /*@__PURE__*/
  enumDesc(file_bilibili_broadcast_v1_push, 2, 0);

/**
 * 消息类型
 *
 * @generated from enum bilibili.broadcast.v1.PushMessageResp.Type
 */
export enum PushMessageResp_Type {
  /**
   * 未知
   *
   * @generated from enum value: TYPE_UNKNOWN = 0;
   */
  UNKNOWN = 0,

  /**
   * 默认
   *
   * @generated from enum value: TYPE_DEFAULT = 1;
   */
  DEFAULT = 1,

  /**
   * 热门
   *
   * @generated from enum value: TYPE_HOT = 2;
   */
  HOT = 2,

  /**
   * 实时
   *
   * @generated from enum value: TYPE_REALTIME = 3;
   */
  REALTIME = 3,

  /**
   * 推荐
   *
   * @generated from enum value: TYPE_RECOMMEND = 4;
   */
  RECOMMEND = 4,
}

/**
 * Describes the enum bilibili.broadcast.v1.PushMessageResp.Type.
 */
export const PushMessageResp_TypeSchema: GenEnum<PushMessageResp_Type> = /*@__PURE__*/
  enumDesc(file_bilibili_broadcast_v1_push, 2, 1);

/**
 * 展示未知
 *
 * @generated from enum bilibili.broadcast.v1.PushMessageResp.Position
 */
export enum PushMessageResp_Position {
  /**
   * 未知
   *
   * @generated from enum value: POS_UNKNOWN = 0;
   */
  POS_UNKNOWN = 0,

  /**
   * 顶部
   *
   * @generated from enum value: POS_TOP = 1;
   */
  POS_TOP = 1,
}

/**
 * Describes the enum bilibili.broadcast.v1.PushMessageResp.Position.
 */
export const PushMessageResp_PositionSchema: GenEnum<PushMessageResp_Position> = /*@__PURE__*/
  enumDesc(file_bilibili_broadcast_v1_push, 2, 2);

/**
 * @generated from message bilibili.broadcast.v1.TargetResource
 */
export type TargetResource = Message<"bilibili.broadcast.v1.TargetResource"> & {
  /**
   * 直播:   roomid
   * UGC:   avid
   * PGC:   seasonid
   * Story: avid
   * 举个例子
   * Type: LINK_TYPE_BANGUMI (番剧)
   * Resource: {"seasonid":"123"}
   *
   * Type: LINK_TYPE_VIDEO (视频)
   * Resource: {"avid":"123"}
   *
   * Type: LINK_TYPE_LIVE (直播)
   * Resource: {"roomid":"123"}
   *
   *
   * @generated from field: bilibili.broadcast.v1.LinkType Type = 1;
   */
  Type: LinkType;

  /**
   * @generated from field: map<string, string> Resource = 2;
   */
  Resource: { [key: string]: string };
};

/**
 * Describes the message bilibili.broadcast.v1.TargetResource.
 * Use `create(TargetResourceSchema)` to create a new message.
 */
export const TargetResourceSchema: GenMessage<TargetResource> = /*@__PURE__*/
  messageDesc(file_bilibili_broadcast_v1_push, 3);

/**
 * @generated from enum bilibili.broadcast.v1.LinkType
 */
export enum LinkType {
  /**
   * 未知
   *
   * @generated from enum value: LINK_TYPE_UNKNOWN = 0;
   */
  UNKNOWN = 0,

  /**
   * 番剧
   *
   * @generated from enum value: LINK_TYPE_BANGUMI = 1;
   */
  BANGUMI = 1,

  /**
   * 视频
   *
   * @generated from enum value: LINK_TYPE_VIDEO = 2;
   */
  VIDEO = 2,

  /**
   * 直播
   *
   * @generated from enum value: LINK_TYPE_LIVE = 3;
   */
  LIVE = 3,
}

/**
 * Describes the enum bilibili.broadcast.v1.LinkType.
 */
export const LinkTypeSchema: GenEnum<LinkType> = /*@__PURE__*/
  enumDesc(file_bilibili_broadcast_v1_push, 0);

/**
 * Push
 *
 * @generated from service bilibili.broadcast.v1.Push
 */
export const Push: GenService<{
  /**
   * @generated from rpc bilibili.broadcast.v1.Push.WatchMessage
   */
  watchMessage: {
    methodKind: "server_streaming";
    input: typeof EmptySchema;
    output: typeof PushMessageRespSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_bilibili_broadcast_v1_push, 0);

