// @generated by protoc-gen-es v2.14.1 with parameter "target=ts"
// @generated from file bilibili/broadcast/v1/test.proto (package bilibili.broadcast.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Any, EmptySchema } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_any, file_google_protobuf_empty } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file bilibili/broadcast/v1/test.proto.
 */
export const file_bilibili_broadcast_v1_test: GenFile = /*@__PURE__*/
  fileDesc("CiBiaWxpYmlsaS9icm9hZGNhc3QvdjEvdGVzdC5wcm90bxIVYmlsaWJpbGkuYnJvYWRjYXN0LnYxIiEKCUFkZFBhcmFtcxIJCgFhGAEgASgFEgkKAWIYAiABKAUiFgoJQWRkUmVzdWx0EgkKAXIYASABKAUiYwoIVGVzdFJlc3ASDgoGdGFza2lkGAEgASgDEhEKCXRpbWVzdGFtcBgCIAEoAxIPCgdtZXNzYWdlGAMgASgJEiMKBWV4dHJhGAQgASgLMhQuZ29vZ2xlLnByb3RvYnVmLkFueTJTCgRUZXN0EksKDldhdGNoVGVzdEV2ZW50EhYuZ29vZ2xlLnByb3RvYnVmLkVtcHR5Gh8uYmlsaWJpbGkuYnJvYWRjYXN0LnYxLlRlc3RSZXNwMAEySQoFVGVzdDISQAoEVGVzdBIgLmJpbGliaWxpLmJyb2FkY2FzdC52MS5BZGRQYXJhbXMaFi5nb29nbGUucHJvdG9idWYuRW1wdHliBnByb3RvMw", [file_google_protobuf_any, file_google_protobuf_empty]);

/**
 * @generated from message bilibili.broadcast.v1.AddParams
 */
export type AddParams = Message<"bilibili.broadcast.v1.AddParams"> & {
  /**
   * @generated from field: int32 a = 1;
   */
  a: number;

  /**
   * @generated from field: int32 b = 2;
   */
  b: number;
};

/**
 * Describes the message bilibili.broadcast.v1.AddParams.
 * Use `create(AddParamsSchema)` to create a new message.
 */
export const AddParamsSchema: GenMessage<AddParams> = /*@__PURE__*/
  messageDesc(file_bilibili_broadcast_v1_test, 0);

/**
 * @generated from message bilibili.broadcast.v1.AddResult
 */
export type AddResult = Message<"bilibili.broadcast.v1.AddResult"> & {
  /**
   * @generated from field: int32 r = 1;
   */
  r: number;
};

/**
 * Describes the message bilibili.broadcast.v1.AddResult.
 * Use `create(AddResultSchema)` to create a new message.
 */
export const AddResultSchema: GenMessage<AddResult> = /*@__PURE__*/
  messageDesc(file_bilibili_broadcast_v1_test, 1);

/**
 * @generated from message bilibili.broadcast.v1.TestResp
 */
export type TestResp = Message<"bilibili.broadcast.v1.TestResp"> & {
  /**
   * 任务id
   *
   * @generated from field: int64 taskid = 1;
   */
  taskid: bigint;

  /**
   * 时间戳
   *
   * @generated from field: int64 timestamp = 2;
   */
  timestamp: bigint;

  /**
   * 消息
   *
   * @generated from field: string message = 3;
   */
  message: string;

  /**
   * 扩展
   *
   * @generated from field: google.protobuf.Any extra = 4;
   */
  extra?: Any | undefined;
};

/**
 * Describes the message bilibili.broadcast.v1.TestResp.
 * Use `create(TestRespSchema)` to create a new message.
 */
export const TestRespSchema: GenMessage<TestResp> = /*@__PURE__*/
  messageDesc(file_bilibili_broadcast_v1_test, 2);

/**
 * Test
 *
 * @generated from service bilibili.broadcast.v1.Test
 */
export const Test: GenService<{
  /**
   * 监听上报事件
   *
   * @generated from rpc bilibili.broadcast.v1.Test.WatchTestEvent
   */
  watchTestEvent: {
    methodKind: "server_streaming";
    input: typeof EmptySchema;
    output: typeof TestRespSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_bilibili_broadcast_v1_test, 0);

/**
 * @generated from service bilibili.broadcast.v1.Test2
 */
export const Test2: GenService<{
  /**
   * @generated from rpc bilibili.broadcast.v1.Test2.Test
   */
  test: {
    methodKind: "unary";
    input: typeof AddParamsSchema;
    output: typeof EmptySchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_bilibili_broadcast_v1_test, 1);

