// @generated by protoc-gen-es v2.14.1 with parameter "target=ts"
// @generated from file bilibili/app/click/v1/heartbeat.proto (package bilibili.app.click.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file bilibili/app/click/v1/heartbeat.proto.
 */
export const file_bilibili_app_click_v1_heartbeat: GenFile = /*@__PURE__*/
  fileDesc("CiViaWxpYmlsaS9hcHAvY2xpY2svdjEvaGVhcnRiZWF0LnByb3RvEhViaWxpYmlsaS5hcHAuY2xpY2sudjEiGgoLQWNjb3VudEluZm8SCwoDbWlkGAEgASgEIj0KB0FwcEluZm8SFgoOdG9wX3BhZ2VfY2xhc3MYASABKAkSDQoFZnRpbWUYAiABKAMSCwoDZGlkGAMgASgJIicKBUV4dHJhEg8KB3Nlc3Npb24YASABKAkSDQoFcmVmZXIYAiABKAkiEAoOSGVhcnRCZWF0UmVwbHki7AMKDEhlYXJ0QmVhdFJlcRISCgpzZXNzaW9uX3YyGAEgASgJEisKBXN0YWdlGAIgASgOMhwuYmlsaWJpbGkuYXBwLmNsaWNrLnYxLlN0YWdlEhYKDnN0cmVhbV90aW1lb3V0GAMgASgEEhcKD2JhdGNoX2ZyZXF1ZW5jeRgEIAEoBBIRCglmcmVxdWVuY3kYBSABKAISNAoKdmlkZW9fbWV0YRgGIAEoCzIgLmJpbGliaWxpLmFwcC5jbGljay52MS5WaWRlb01ldGESMAoIYXBwX2luZm8YByABKAsyHi5iaWxpYmlsaS5hcHAuY2xpY2sudjEuQXBwSW5mbxI4CgxhY2NvdW50X2luZm8YCCABKAsyIi5iaWxpYmlsaS5hcHAuY2xpY2sudjEuQWNjb3VudEluZm8SQwoScHJlX3Byb2Nlc3NfcmVzdWx0GAkgASgLMicuYmlsaWJpbGkuYXBwLmNsaWNrLnYxLlByZVByb2Nlc3NSZXN1bHQSOgoNcGxheWVyX3N0YXR1cxgKIAMoCzIjLmJpbGliaWxpLmFwcC5jbGljay52MS5QbGF5ZXJTdGF0dXMSNAoKdmlkZW9faW5mbxgLIAEoCzIgLmJpbGliaWxpLmFwcC5jbGljay52MS5WaWRlb0luZm8igwEKDFBsYXllclN0YXR1cxIVCg1wbGF5YmFja19yYXRlGAEgASgCEhAKCHByb2dyZXNzGAIgASgEEjQKCnBsYXlfc3RhdGUYAyABKA4yIC5iaWxpYmlsaS5hcHAuY2xpY2sudjEuUGxheVN0YXRlEhQKDGlzX2J1ZmZlcmluZxgEIAEoCCIeChBQcmVQcm9jZXNzUmVzdWx0EgoKAnZ0GAEgASgDIiEKCVZpZGVvSW5mbxIUCgxjaWRfZHVyYXRpb24YASABKAQiJQoJVmlkZW9NZXRhEgsKA2FpZBgBIAEoBBILCgNjaWQYAiABKAQqbQoJUGxheVN0YXRlEhEKDVNUQVRFX1VOS05PV04QABINCglQUkVQQVJJTkcQARIMCghQUkVQQVJFRBACEgsKB1BMQVlJTkcQAxIKCgZQQVVTRUQQBBILCgdTVE9QUEVEEAUSCgoGRkFJTEVEEAYqOgoFU3RhZ2USEQoNU1RBR0VfVU5LTk9XThAAEgkKBVNUQVJUEAESBwoDRU5EEAISCgoGU0FNUExFEAMyYAoFQ2xpY2sSVwoJSGVhcnRCZWF0EiMuYmlsaWJpbGkuYXBwLmNsaWNrLnYxLkhlYXJ0QmVhdFJlcRolLmJpbGliaWxpLmFwcC5jbGljay52MS5IZWFydEJlYXRSZXBseWIGcHJvdG8z");

/**
 * 账户信息
 *
 * @generated from message bilibili.app.click.v1.AccountInfo
 */
export type AccountInfo = Message<"bilibili.app.click.v1.AccountInfo"> & {
  /**
   * 
   *
   * @generated from field: uint64 mid = 1;
   */
  mid: bigint;
};

/**
 * Describes the message bilibili.app.click.v1.AccountInfo.
 * Use `create(AccountInfoSchema)` to create a new message.
 */
export const AccountInfoSchema: GenMessage<AccountInfo> = /*@__PURE__*/
  messageDesc(file_bilibili_app_click_v1_heartbeat, 0);

/**
 * 
 *
 * @generated from message bilibili.app.click.v1.AppInfo
 */
export type AppInfo = Message<"bilibili.app.click.v1.AppInfo"> & {
  /**
   * 
   *
   * @generated from field: string top_page_class = 1;
   */
  topPageClass: string;

  /**
   * 客户端首次启动时的毫秒时间戳
   *
   * @generated from field: int64 ftime = 2;
   */
  ftime: bigint;

  /**
   * 
   *
   * @generated from field: string did = 3;
   */
  did: string;
};

/**
 * Describes the message bilibili.app.click.v1.AppInfo.
 * Use `create(AppInfoSchema)` to create a new message.
 */
export const AppInfoSchema: GenMessage<AppInfo> = /*@__PURE__*/
  messageDesc(file_bilibili_app_click_v1_heartbeat, 1);

/**
 * 心跳补充信息
 *
 * @generated from message bilibili.app.click.v1.Extra
 */
export type Extra = Message<"bilibili.app.click.v1.Extra"> & {
  /**
   * 
   *
   * @generated from field: string session = 1;
   */
  session: string;

  /**
   * 
   *
   * @generated from field: string refer = 2;
   */
  refer: string;
};

/**
 * Describes the message bilibili.app.click.v1.Extra.
 * Use `create(ExtraSchema)` to create a new message.
 */
export const ExtraSchema: GenMessage<Extra> = /*@__PURE__*/
  messageDesc(file_bilibili_app_click_v1_heartbeat, 2);

/**
 * @generated from message bilibili.app.click.v1.HeartBeatReply
 */
export type HeartBeatReply = Message<"bilibili.app.click.v1.HeartBeatReply"> & {
};

/**
 * Describes the message bilibili.app.click.v1.HeartBeatReply.
 * Use `create(HeartBeatReplySchema)` to create a new message.
 */
export const HeartBeatReplySchema: GenMessage<HeartBeatReply> = /*@__PURE__*/
  messageDesc(file_bilibili_app_click_v1_heartbeat, 3);

/**
 * 
 *
 * @generated from message bilibili.app.click.v1.HeartBeatReq
 */
export type HeartBeatReq = Message<"bilibili.app.click.v1.HeartBeatReq"> & {
  /**
   * 
   *
   * @generated from field: string session_v2 = 1;
   */
  sessionV2: string;

  /**
   * 
   *
   * @generated from field: bilibili.app.click.v1.Stage stage = 2;
   */
  stage: Stage;

  /**
   * 流加载失败timeout
   *
   * @generated from field: uint64 stream_timeout = 3;
   */
  streamTimeout: bigint;

  /**
   * 
   *
   * @generated from field: uint64 batch_frequency = 4;
   */
  batchFrequency: bigint;

  /**
   * 
   *
   * @generated from field: float frequency = 5;
   */
  frequency: number;

  /**
   * 
   *
   * @generated from field: bilibili.app.click.v1.VideoMeta video_meta = 6;
   */
  videoMeta?: VideoMeta | undefined;

  /**
   * 
   *
   * @generated from field: bilibili.app.click.v1.AppInfo app_info = 7;
   */
  appInfo?: AppInfo | undefined;

  /**
   * 
   *
   * @generated from field: bilibili.app.click.v1.AccountInfo account_info = 8;
   */
  accountInfo?: AccountInfo | undefined;

  /**
   * 
   *
   * @generated from field: bilibili.app.click.v1.PreProcessResult pre_process_result = 9;
   */
  preProcessResult?: PreProcessResult | undefined;

  /**
   * 
   *
   * @generated from field: repeated bilibili.app.click.v1.PlayerStatus player_status = 10;
   */
  playerStatus: PlayerStatus[];

  /**
   * 
   *
   * @generated from field: bilibili.app.click.v1.VideoInfo video_info = 11;
   */
  videoInfo?: VideoInfo | undefined;
};

/**
 * Describes the message bilibili.app.click.v1.HeartBeatReq.
 * Use `create(HeartBeatReqSchema)` to create a new message.
 */
export const HeartBeatReqSchema: GenMessage<HeartBeatReq> = /*@__PURE__*/
  messageDesc(file_bilibili_app_click_v1_heartbeat, 4);

/**
 * 
 *
 * @generated from message bilibili.app.click.v1.PlayerStatus
 */
export type PlayerStatus = Message<"bilibili.app.click.v1.PlayerStatus"> & {
  /**
   * 
   *
   * @generated from field: float playback_rate = 1;
   */
  playbackRate: number;

  /**
   * 
   *
   * @generated from field: uint64 progress = 2;
   */
  progress: bigint;

  /**
   * 
   *
   * @generated from field: bilibili.app.click.v1.PlayState play_state = 3;
   */
  playState: PlayState;

  /**
   * 
   *
   * @generated from field: bool is_buffering = 4;
   */
  isBuffering: boolean;
};

/**
 * Describes the message bilibili.app.click.v1.PlayerStatus.
 * Use `create(PlayerStatusSchema)` to create a new message.
 */
export const PlayerStatusSchema: GenMessage<PlayerStatus> = /*@__PURE__*/
  messageDesc(file_bilibili_app_click_v1_heartbeat, 5);

/**
 * 
 *
 * @generated from message bilibili.app.click.v1.PreProcessResult
 */
export type PreProcessResult = Message<"bilibili.app.click.v1.PreProcessResult"> & {
  /**
   * 
   *
   * @generated from field: int64 vt = 1;
   */
  vt: bigint;
};

/**
 * Describes the message bilibili.app.click.v1.PreProcessResult.
 * Use `create(PreProcessResultSchema)` to create a new message.
 */
export const PreProcessResultSchema: GenMessage<PreProcessResult> = /*@__PURE__*/
  messageDesc(file_bilibili_app_click_v1_heartbeat, 6);

/**
 * 
 *
 * @generated from message bilibili.app.click.v1.VideoInfo
 */
export type VideoInfo = Message<"bilibili.app.click.v1.VideoInfo"> & {
  /**
   * 
   *
   * @generated from field: uint64 cid_duration = 1;
   */
  cidDuration: bigint;
};

/**
 * Describes the message bilibili.app.click.v1.VideoInfo.
 * Use `create(VideoInfoSchema)` to create a new message.
 */
export const VideoInfoSchema: GenMessage<VideoInfo> = /*@__PURE__*/
  messageDesc(file_bilibili_app_click_v1_heartbeat, 7);

/**
 * 
 *
 * @generated from message bilibili.app.click.v1.VideoMeta
 */
export type VideoMeta = Message<"bilibili.app.click.v1.VideoMeta"> & {
  /**
   * 
   *
   * @generated from field: uint64 aid = 1;
   */
  aid: bigint;

  /**
   * 
   *
   * @generated from field: uint64 cid = 2;
   */
  cid: bigint;
};

/**
 * Describes the message bilibili.app.click.v1.VideoMeta.
 * Use `create(VideoMetaSchema)` to create a new message.
 */
export const VideoMetaSchema: GenMessage<VideoMeta> = /*@__PURE__*/
  messageDesc(file_bilibili_app_click_v1_heartbeat, 8);

/**
 * 
 *
 * @generated from enum bilibili.app.click.v1.PlayState
 */
export enum PlayState {
  /**
   * 
   *
   * @generated from enum value: STATE_UNKNOWN = 0;
   */
  STATE_UNKNOWN = 0,

  /**
   * 
   *
   * @generated from enum value: PREPARING = 1;
   */
  PREPARING = 1,

  /**
   * 
   *
   * @generated from enum value: PREPARED = 2;
   */
  PREPARED = 2,

  /**
   * 
   *
   * @generated from enum value: PLAYING = 3;
   */
  PLAYING = 3,

  /**
   * 
   *
   * @generated from enum value: PAUSED = 4;
   */
  PAUSED = 4,

  /**
   * 
   *
   * @generated from enum value: STOPPED = 5;
   */
  STOPPED = 5,

  /**
   * 
   *
   * @generated from enum value: FAILED = 6;
   */
  FAILED = 6,
}

/**
 * Describes the enum bilibili.app.click.v1.PlayState.
 */
export const PlayStateSchema: GenEnum<PlayState> = /*@__PURE__*/
  enumDesc(file_bilibili_app_click_v1_heartbeat, 0);

/**
 * 
 *
 * @generated from enum bilibili.app.click.v1.Stage
 */
export enum Stage {
  /**
   * 
   *
   * @generated from enum value: STAGE_UNKNOWN = 0;
   */
  STAGE_UNKNOWN = 0,

  /**
   * 
   *
   * @generated from enum value: START = 1;
   */
  START = 1,

  /**
   * 
   *
   * @generated from enum value: END = 2;
   */
  END = 2,

  /**
   * 
   *
   * @generated from enum value: SAMPLE = 3;
   */
  SAMPLE = 3,
}

/**
 * Describes the enum bilibili.app.click.v1.Stage.
 */
export const StageSchema: GenEnum<Stage> = /*@__PURE__*/
  enumDesc(file_bilibili_app_click_v1_heartbeat, 1);

/**
 * @generated from service bilibili.app.click.v1.Click
 */
export const Click: GenService<{
  /**
   * 客户端心跳上传
   *
   * @generated from rpc bilibili.app.click.v1.Click.HeartBeat
   */
  heartBeat: {
    methodKind: "unary";
    input: typeof HeartBeatReqSchema;
    output: typeof HeartBeatReplySchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_bilibili_app_click_v1_heartbeat, 0);

