// @generated by protoc-gen-es v2.14.1 with parameter "target=ts"
// @generated from file bilibili/broadcast/message/im/notify.proto (package bilibili.broadcast.message.im, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { EmptySchema } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_empty } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file bilibili/broadcast/message/im/notify.proto.
 */
export const file_bilibili_broadcast_message_im_notify: GenFile = /*@__PURE__*/
  fileDesc("CipiaWxpYmlsaS9icm9hZGNhc3QvbWVzc2FnZS9pbS9ub3RpZnkucHJvdG8SHWJpbGliaWxpLmJyb2FkY2FzdC5tZXNzYWdlLmltInMKCU5vdGlmeVJzcBILCgN1aWQYASABKAQSCwoDY21kGAIgASgEEg8KB3BheWxvYWQYAyABKAwSOwoMcGF5bG9hZF90eXBlGAQgASgOMiUuYmlsaWJpbGkuYnJvYWRjYXN0Lm1lc3NhZ2UuaW0uUExUeXBlItgCCgNNc2cSEgoKc2VuZGVyX3VpZBgBIAEoBBIVCg1yZWNlaXZlcl90eXBlGAIgASgFEhMKC3JlY2VpdmVyX2lkGAMgASgEEhIKCmNsaV9tc2dfaWQYBCABKAQSEAoIbXNnX3R5cGUYBSABKAUSDwoHY29udGVudBgGIAEoCRIRCgltc2dfc2Vxbm8YByABKAQSEQoJdGltZXN0YW1wGAggASgEEg8KB2F0X3VpZHMYCSADKAQSEgoKcmVjdmVyX2lkcxgKIAMoBBIPCgdtc2dfa2V5GAsgASgEEhIKCm1zZ19zdGF0dXMYDCABKA0SEgoKc3lzX2NhbmNlbBgNIAEoCBIVCg1pc19tdWx0aV9jaGF0GA4gASgNEhYKDndpdGhkcmF3X3NlcW5vGA8gASgEEhMKC25vdGlmeV9jb2RlGBAgASgJEhIKCm1zZ19zb3VyY2UYESABKA0iRwoKTm90aWZ5SW5mbxIQCghtc2dfdHlwZRgBIAEoDRIRCgl0YWxrZXJfaWQYAiABKAQSFAoMc2Vzc2lvbl90eXBlGAMgASgNIqEBCg9SZXFTZXJ2ZXJOb3RpZnkSFQoNbGFzdGVzdF9zZXFubxgBIAEoBBI3CgtpbnN0YW50X21zZxgCIAEoCzIiLmJpbGliaWxpLmJyb2FkY2FzdC5tZXNzYWdlLmltLk1zZxI+Cgtub3RpZnlfaW5mbxgDIAEoCzIpLmJpbGliaWxpLmJyb2FkY2FzdC5tZXNzYWdlLmltLk5vdGlmeUluZm8qNgoGUExUeXBlEhUKEUVOX1BBWUxPQURfTk9STUFMEAASFQoRRU5fUEFZTE9BRF9CQVNFNjQQASpQCgVDbWRJZBIVChFFTl9DTURfSURfSU5WQUxJRBAAEhgKFEVOX0NNRF9JRF9NU0dfTk9USUZZEAESFgoSRU5fQ01EX0lEX0tJQ0tfT1VUEAIyWwoGTm90aWZ5ElEKC1dhdGNoTm90aWZ5EhYuZ29vZ2xlLnByb3RvYnVmLkVtcHR5GiguYmlsaWJpbGkuYnJvYWRjYXN0Lm1lc3NhZ2UuaW0uTm90aWZ5UnNwMAFiBnByb3RvMw", [file_google_protobuf_empty]);

/**
 * @generated from message bilibili.broadcast.message.im.NotifyRsp
 */
export type NotifyRsp = Message<"bilibili.broadcast.message.im.NotifyRsp"> & {
  /**
   * @generated from field: uint64 uid = 1;
   */
  uid: bigint;

  /**
   * 命令id
   *
   * @generated from field: uint64 cmd = 2;
   */
  cmd: bigint;

  /**
   * @generated from field: bytes payload = 3;
   */
  payload: Uint8Array;

  /**
   * @generated from field: bilibili.broadcast.message.im.PLType payload_type = 4;
   */
  payloadType: PLType;
};

/**
 * Describes the message bilibili.broadcast.message.im.NotifyRsp.
 * Use `create(NotifyRspSchema)` to create a new message.
 */
export const NotifyRspSchema: GenMessage<NotifyRsp> = /*@__PURE__*/
  messageDesc(file_bilibili_broadcast_message_im_notify, 0);

/**
 * @generated from message bilibili.broadcast.message.im.Msg
 */
export type Msg = Message<"bilibili.broadcast.message.im.Msg"> & {
  /**
   * 发送方uid
   *
   * @generated from field: uint64 sender_uid = 1;
   */
  senderUid: bigint;

  /**
   * 接收方类型
   *
   * @generated from field: int32 receiver_type = 2;
   */
  receiverType: number;

  /**
   * 接收方id
   *
   * @generated from field: uint64 receiver_id = 3;
   */
  receiverId: bigint;

  /**
   * 客户端的序列id 用于服务端去重
   *
   * @generated from field: uint64 cli_msg_id = 4;
   */
  cliMsgId: bigint;

  /**
   * 消息类型
   *
   * @generated from field: int32 msg_type = 5;
   */
  msgType: number;

  /**
   * 消息内容
   *
   * @generated from field: string content = 6;
   */
  content: string;

  /**
   * 服务端的序列号
   *
   * @generated from field: uint64 msg_seqno = 7;
   */
  msgSeqno: bigint;

  /**
   * 消息发送时间（服务端时间）
   *
   * @generated from field: uint64 timestamp = 8;
   */
  timestamp: bigint;

  /**
   * at用户列表
   *
   * @generated from field: repeated uint64 at_uids = 9;
   */
  atUids: bigint[];

  /**
   * 多人消息
   *
   * @generated from field: repeated uint64 recver_ids = 10;
   */
  recverIds: bigint[];

  /**
   * 消息唯一标示
   *
   * @generated from field: uint64 msg_key = 11;
   */
  msgKey: bigint;

  /**
   * 消息状态
   *
   * @generated from field: uint32 msg_status = 12;
   */
  msgStatus: number;

  /**
   * 是否为系统撤销
   *
   * @generated from field: bool sys_cancel = 13;
   */
  sysCancel: boolean;

  /**
   * 是否是多聊消息 目前群通知管理员的部分通知属于该类消息
   *
   * @generated from field: uint32 is_multi_chat = 14;
   */
  isMultiChat: number;

  /**
   * 表示撤回的消息的session_seqno 用以后续的比较 实现未读数的正确显示
   *
   * @generated from field: uint64 withdraw_seqno = 15;
   */
  withdrawSeqno: bigint;

  /**
   * 通知码
   *
   * @generated from field: string notify_code = 16;
   */
  notifyCode: string;

  /**
   * 消息来源
   *
   * @generated from field: uint32 msg_source = 17;
   */
  msgSource: number;
};

/**
 * Describes the message bilibili.broadcast.message.im.Msg.
 * Use `create(MsgSchema)` to create a new message.
 */
export const MsgSchema: GenMessage<Msg> = /*@__PURE__*/
  messageDesc(file_bilibili_broadcast_message_im_notify, 1);

/**
 * @generated from message bilibili.broadcast.message.im.NotifyInfo
 */
export type NotifyInfo = Message<"bilibili.broadcast.message.im.NotifyInfo"> & {
  /**
   * @generated from field: uint32 msg_type = 1;
   */
  msgType: number;

  /**
   * @generated from field: uint64 talker_id = 2;
   */
  talkerId: bigint;

  /**
   * @generated from field: uint32 session_type = 3;
   */
  sessionType: number;
};

/**
 * Describes the message bilibili.broadcast.message.im.NotifyInfo.
 * Use `create(NotifyInfoSchema)` to create a new message.
 */
export const NotifyInfoSchema: GenMessage<NotifyInfo> = /*@__PURE__*/
  messageDesc(file_bilibili_broadcast_message_im_notify, 2);

/**
 * @generated from message bilibili.broadcast.message.im.ReqServerNotify
 */
export type ReqServerNotify = Message<"bilibili.broadcast.message.im.ReqServerNotify"> & {
  /**
   * 最新序列号
   *
   * @generated from field: uint64 lastest_seqno = 1;
   */
  lastestSeqno: bigint;

  /**
   * 即时消息 该类消息主要用于系统通知 当客户端sync msg时 不会sync到此类消息
   *
   * @generated from field: bilibili.broadcast.message.im.Msg instant_msg = 2;
   */
  instantMsg?: Msg | undefined;

  /**
   * @generated from field: bilibili.broadcast.message.im.NotifyInfo notify_info = 3;
   */
  notifyInfo?: NotifyInfo | undefined;
};

/**
 * Describes the message bilibili.broadcast.message.im.ReqServerNotify.
 * Use `create(ReqServerNotifySchema)` to create a new message.
 */
export const ReqServerNotifySchema: GenMessage<ReqServerNotify> = /*@__PURE__*/
  messageDesc(file_bilibili_broadcast_message_im_notify, 3);

/**
 * @generated from enum bilibili.broadcast.message.im.PLType
 */
export enum PLType {
  /**
   * @generated from enum value: EN_PAYLOAD_NORMAL = 0;
   */
  EN_PAYLOAD_NORMAL = 0,

  /**
   * @generated from enum value: EN_PAYLOAD_BASE64 = 1;
   */
  EN_PAYLOAD_BASE64 = 1,
}

/**
 * Describes the enum bilibili.broadcast.message.im.PLType.
 */
export const PLTypeSchema: GenEnum<PLType> = /*@__PURE__*/
  enumDesc(file_bilibili_broadcast_message_im_notify, 0);

/**
 * @generated from enum bilibili.broadcast.message.im.CmdId
 */
export enum CmdId {
  /**
   * 非法cmd
   *
   * @generated from enum value: EN_CMD_ID_INVALID = 0;
   */
  EN_CMD_ID_INVALID = 0,

  /**
   * 服务端主动发起
   *
   * @generated from enum value: EN_CMD_ID_MSG_NOTIFY = 1;
   */
  EN_CMD_ID_MSG_NOTIFY = 1,

  /**
   * @generated from enum value: EN_CMD_ID_KICK_OUT = 2;
   */
  EN_CMD_ID_KICK_OUT = 2,
}

/**
 * Describes the enum bilibili.broadcast.message.im.CmdId.
 */
export const CmdIdSchema: GenEnum<CmdId> = /*@__PURE__*/
  enumDesc(file_bilibili_broadcast_message_im_notify, 1);

/**
 * @generated from service bilibili.broadcast.message.im.Notify
 */
export const Notify: GenService<{
  /**
   * @generated from rpc bilibili.broadcast.message.im.Notify.WatchNotify
   */
  watchNotify: {
    methodKind: "server_streaming";
    input: typeof EmptySchema;
    output: typeof NotifyRspSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_bilibili_broadcast_message_im_notify, 0);

