// @generated by protoc-gen-es v2.14.1 with parameter "target=ts"
// @generated from file bilibili/dagw/component/avatar/v1/plugin.proto (package bilibili.dagw.component.avatar.v1.plugin, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { ColorConfig } from "../common/common_pb";
import { file_bilibili_dagw_component_avatar_common_common } from "../common/common_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file bilibili/dagw/component/avatar/v1/plugin.proto.
 */
export const file_bilibili_dagw_component_avatar_v1_plugin: GenFile = /*@__PURE__*/
  fileDesc("Ci5iaWxpYmlsaS9kYWd3L2NvbXBvbmVudC9hdmF0YXIvdjEvcGx1Z2luLnByb3RvEihiaWxpYmlsaS5kYWd3LmNvbXBvbmVudC5hdmF0YXIudjEucGx1Z2luIn8KGENvbW1lbnREb3VibGVDbGlja0NvbmZpZxJKCgtpbnRlcmFjdGlvbhgBIAEoCzI1LmJpbGliaWxpLmRhZ3cuY29tcG9uZW50LmF2YXRhci52MS5wbHVnaW4uSW50ZXJhY3Rpb24SFwoPYW5pbWF0aW9uX3NjYWxlGAIgASgBIlUKCkd5cm9Db25maWcSRwoJZ3lyb3Njb3BlGAEgASgLMjQuYmlsaWJpbGkuZGFndy5jb21wb25lbnQuYXZhdGFyLnYxLnBsdWdpbi5ORlRJbWFnZVYyIpQBChJHeXJvc2NvcGVDb250ZW50VjISEAoIZmlsZV91cmwYASABKAkSDQoFc2NhbGUYAiABKAISXQoUcGh5c2ljYWxfb3JpZW50YXRpb24YAyADKAsyPy5iaWxpYmlsaS5kYWd3LmNvbXBvbmVudC5hdmF0YXIudjEucGx1Z2luLlBoeXNpY2FsT3JpZW50YXRpb25WMiJ5ChFHeXJvc2NvcGVFbnRpdHlWMhIUCgxkaXNwbGF5X3R5cGUYASABKAkSTgoIY29udGVudHMYAiADKAsyPC5iaWxpYmlsaS5kYWd3LmNvbXBvbmVudC5hdmF0YXIudjEucGx1Z2luLkd5cm9zY29wZUNvbnRlbnRWMiJTCgtJbnRlcmFjdGlvbhIOCgZuZnRfaWQYASABKAkSDwoHZW5hYmxlZBgCIAEoCBINCgVpdHlwZRgDIAEoCRIUCgxtZXRhZGF0YV91cmwYBCABKAkiIgoPTGl2ZUFuaW1lQ29uZmlnEg8KB2lzX2xpdmUYASABKAgitgEKDUxpdmVBbmltZUl0ZW0SQQoFY29sb3IYASABKAsyMi5iaWxpYmlsaS5kYWd3LmNvbXBvbmVudC5hdmF0YXIuY29tbW9uLkNvbG9yQ29uZmlnEhMKC3N0YXJ0X3JhdGlvGAIgASgBEhEKCWVuZF9yYXRpbxgDIAEoARIUCgxzdGFydF9zdHJva2UYBCABKAESFQoNc3RhcnRfb3BhY2l0eRgFIAEoARINCgVwaGFzZRgGIAEoAyJcCgpORlRJbWFnZVYyEk4KCWd5cm9zY29wZRgBIAMoCzI7LmJpbGliaWxpLmRhZ3cuY29tcG9uZW50LmF2YXRhci52MS5wbHVnaW4uR3lyb3Njb3BlRW50aXR5VjIiPAocUGh5c2ljYWxPcmllbnRhdGlvbkFuaW1hdGlvbhIMCgR0eXBlGAEgASgJEg4KBmJlemllchgDIAEoCSKBAQoVUGh5c2ljYWxPcmllbnRhdGlvblYyEgwKBHR5cGUYASABKAkSWgoKYW5pbWF0aW9ucxgDIAMoCzJGLmJpbGliaWxpLmRhZ3cuY29tcG9uZW50LmF2YXRhci52MS5wbHVnaW4uUGh5c2ljYWxPcmllbnRhdGlvbkFuaW1hdGlvbmIGcHJvdG8z", [file_bilibili_dagw_component_avatar_common_common]);

/**
 * @generated from message bilibili.dagw.component.avatar.v1.plugin.CommentDoubleClickConfig
 */
export type CommentDoubleClickConfig = Message<"bilibili.dagw.component.avatar.v1.plugin.CommentDoubleClickConfig"> & {
  /**
   * @generated from field: bilibili.dagw.component.avatar.v1.plugin.Interaction interaction = 1;
   */
  interaction?: Interaction | undefined;

  /**
   * @generated from field: double animation_scale = 2;
   */
  animationScale: number;
};

/**
 * Describes the message bilibili.dagw.component.avatar.v1.plugin.CommentDoubleClickConfig.
 * Use `create(CommentDoubleClickConfigSchema)` to create a new message.
 */
export const CommentDoubleClickConfigSchema: GenMessage<CommentDoubleClickConfig> = /*@__PURE__*/
  messageDesc(file_bilibili_dagw_component_avatar_v1_plugin, 0);

/**
 * @generated from message bilibili.dagw.component.avatar.v1.plugin.GyroConfig
 */
export type GyroConfig = Message<"bilibili.dagw.component.avatar.v1.plugin.GyroConfig"> & {
  /**
   * @generated from field: bilibili.dagw.component.avatar.v1.plugin.NFTImageV2 gyroscope = 1;
   */
  gyroscope?: NFTImageV2 | undefined;
};

/**
 * Describes the message bilibili.dagw.component.avatar.v1.plugin.GyroConfig.
 * Use `create(GyroConfigSchema)` to create a new message.
 */
export const GyroConfigSchema: GenMessage<GyroConfig> = /*@__PURE__*/
  messageDesc(file_bilibili_dagw_component_avatar_v1_plugin, 1);

/**
 * @generated from message bilibili.dagw.component.avatar.v1.plugin.GyroscopeContentV2
 */
export type GyroscopeContentV2 = Message<"bilibili.dagw.component.avatar.v1.plugin.GyroscopeContentV2"> & {
  /**
   * @generated from field: string file_url = 1;
   */
  fileUrl: string;

  /**
   * @generated from field: float scale = 2;
   */
  scale: number;

  /**
   * @generated from field: repeated bilibili.dagw.component.avatar.v1.plugin.PhysicalOrientationV2 physical_orientation = 3;
   */
  physicalOrientation: PhysicalOrientationV2[];
};

/**
 * Describes the message bilibili.dagw.component.avatar.v1.plugin.GyroscopeContentV2.
 * Use `create(GyroscopeContentV2Schema)` to create a new message.
 */
export const GyroscopeContentV2Schema: GenMessage<GyroscopeContentV2> = /*@__PURE__*/
  messageDesc(file_bilibili_dagw_component_avatar_v1_plugin, 2);

/**
 * @generated from message bilibili.dagw.component.avatar.v1.plugin.GyroscopeEntityV2
 */
export type GyroscopeEntityV2 = Message<"bilibili.dagw.component.avatar.v1.plugin.GyroscopeEntityV2"> & {
  /**
   * @generated from field: string display_type = 1;
   */
  displayType: string;

  /**
   * @generated from field: repeated bilibili.dagw.component.avatar.v1.plugin.GyroscopeContentV2 contents = 2;
   */
  contents: GyroscopeContentV2[];
};

/**
 * Describes the message bilibili.dagw.component.avatar.v1.plugin.GyroscopeEntityV2.
 * Use `create(GyroscopeEntityV2Schema)` to create a new message.
 */
export const GyroscopeEntityV2Schema: GenMessage<GyroscopeEntityV2> = /*@__PURE__*/
  messageDesc(file_bilibili_dagw_component_avatar_v1_plugin, 3);

/**
 * @generated from message bilibili.dagw.component.avatar.v1.plugin.Interaction
 */
export type Interaction = Message<"bilibili.dagw.component.avatar.v1.plugin.Interaction"> & {
  /**
   * @generated from field: string nft_id = 1;
   */
  nftId: string;

  /**
   * @generated from field: bool enabled = 2;
   */
  enabled: boolean;

  /**
   * @generated from field: string itype = 3;
   */
  itype: string;

  /**
   * @generated from field: string metadata_url = 4;
   */
  metadataUrl: string;
};

/**
 * Describes the message bilibili.dagw.component.avatar.v1.plugin.Interaction.
 * Use `create(InteractionSchema)` to create a new message.
 */
export const InteractionSchema: GenMessage<Interaction> = /*@__PURE__*/
  messageDesc(file_bilibili_dagw_component_avatar_v1_plugin, 4);

/**
 * @generated from message bilibili.dagw.component.avatar.v1.plugin.LiveAnimeConfig
 */
export type LiveAnimeConfig = Message<"bilibili.dagw.component.avatar.v1.plugin.LiveAnimeConfig"> & {
  /**
   * @generated from field: bool is_live = 1;
   */
  isLive: boolean;
};

/**
 * Describes the message bilibili.dagw.component.avatar.v1.plugin.LiveAnimeConfig.
 * Use `create(LiveAnimeConfigSchema)` to create a new message.
 */
export const LiveAnimeConfigSchema: GenMessage<LiveAnimeConfig> = /*@__PURE__*/
  messageDesc(file_bilibili_dagw_component_avatar_v1_plugin, 5);

/**
 * @generated from message bilibili.dagw.component.avatar.v1.plugin.LiveAnimeItem
 */
export type LiveAnimeItem = Message<"bilibili.dagw.component.avatar.v1.plugin.LiveAnimeItem"> & {
  /**
   * @generated from field: bilibili.dagw.component.avatar.common.ColorConfig color = 1;
   */
  color?: ColorConfig | undefined;

  /**
   * @generated from field: double start_ratio = 2;
   */
  startRatio: number;

  /**
   * @generated from field: double end_ratio = 3;
   */
  endRatio: number;

  /**
   * @generated from field: double start_stroke = 4;
   */
  startStroke: number;

  /**
   * @generated from field: double start_opacity = 5;
   */
  startOpacity: number;

  /**
   * @generated from field: int64 phase = 6;
   */
  phase: bigint;
};

/**
 * Describes the message bilibili.dagw.component.avatar.v1.plugin.LiveAnimeItem.
 * Use `create(LiveAnimeItemSchema)` to create a new message.
 */
export const LiveAnimeItemSchema: GenMessage<LiveAnimeItem> = /*@__PURE__*/
  messageDesc(file_bilibili_dagw_component_avatar_v1_plugin, 6);

/**
 * @generated from message bilibili.dagw.component.avatar.v1.plugin.NFTImageV2
 */
export type NFTImageV2 = Message<"bilibili.dagw.component.avatar.v1.plugin.NFTImageV2"> & {
  /**
   * @generated from field: repeated bilibili.dagw.component.avatar.v1.plugin.GyroscopeEntityV2 gyroscope = 1;
   */
  gyroscope: GyroscopeEntityV2[];
};

/**
 * Describes the message bilibili.dagw.component.avatar.v1.plugin.NFTImageV2.
 * Use `create(NFTImageV2Schema)` to create a new message.
 */
export const NFTImageV2Schema: GenMessage<NFTImageV2> = /*@__PURE__*/
  messageDesc(file_bilibili_dagw_component_avatar_v1_plugin, 7);

/**
 * @generated from message bilibili.dagw.component.avatar.v1.plugin.PhysicalOrientationAnimation
 */
export type PhysicalOrientationAnimation = Message<"bilibili.dagw.component.avatar.v1.plugin.PhysicalOrientationAnimation"> & {
  /**
   * @generated from field: string type = 1;
   */
  type: string;

  /**
   * @generated from field: string bezier = 3;
   */
  bezier: string;
};

/**
 * Describes the message bilibili.dagw.component.avatar.v1.plugin.PhysicalOrientationAnimation.
 * Use `create(PhysicalOrientationAnimationSchema)` to create a new message.
 */
export const PhysicalOrientationAnimationSchema: GenMessage<PhysicalOrientationAnimation> = /*@__PURE__*/
  messageDesc(file_bilibili_dagw_component_avatar_v1_plugin, 8);

/**
 * @generated from message bilibili.dagw.component.avatar.v1.plugin.PhysicalOrientationV2
 */
export type PhysicalOrientationV2 = Message<"bilibili.dagw.component.avatar.v1.plugin.PhysicalOrientationV2"> & {
  /**
   * @generated from field: string type = 1;
   */
  type: string;

  /**
   * @generated from field: repeated bilibili.dagw.component.avatar.v1.plugin.PhysicalOrientationAnimation animations = 3;
   */
  animations: PhysicalOrientationAnimation[];
};

/**
 * Describes the message bilibili.dagw.component.avatar.v1.plugin.PhysicalOrientationV2.
 * Use `create(PhysicalOrientationV2Schema)` to create a new message.
 */
export const PhysicalOrientationV2Schema: GenMessage<PhysicalOrientationV2> = /*@__PURE__*/
  messageDesc(file_bilibili_dagw_component_avatar_v1_plugin, 9);

