declare module '@env' {
  export const DROPBOX_KEY: string;
  export const DROPBOX_SECRET: string;
  export const DROPBOX_TOKEN: string;
  export const CHROMEAPP_CLIENT_ID: string;
  export const PERSONAL_CLOUD_SERVER: string;
  export const PERSONAL_CLOUD_SECRET: string;
  export const APPSTORE: boolean;
  export const TRACKING: boolean;
  export const GITEE_SECRET: string;
  export const GITEE_KEY: string;
  export const GITHUB_SECRET: string;
  export const GITHUB_KEY: string;
  export const RGAIN_URL: string;
  export const IOSSTORE: boolean;
  export const REVENUECAT_STRIPE: string;
  export const REVENUECAT_GOOGLE: string;
  export const STRIPE_API_KEY: string;
}
