// @generated by protoc-gen-es v2.14.1 with parameter "target=ts"
// @generated from file bilibili/broadcast/message/tv/proj.proto (package bilibili.broadcast.message.tv, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { EmptySchema } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_empty } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file bilibili/broadcast/message/tv/proj.proto.
 */
export const file_bilibili_broadcast_message_tv_proj: GenFile = /*@__PURE__*/
  fileDesc("CihiaWxpYmlsaS9icm9hZGNhc3QvbWVzc2FnZS90di9wcm9qLnByb3RvEh1iaWxpYmlsaS5icm9hZGNhc3QubWVzc2FnZS50diKaAQoJUHJvalJlcGx5EhAKCGNtZF90eXBlGAEgASgDEgsKA21pZBgCIAEoAxILCgNhaWQYAyABKAMSCwoDY2lkGAQgASgDEhIKCnZpZGVvX3R5cGUYBSABKAMSDQoFZXBfaWQYBiABKAMSEQoJc2Vhc29uX2lkGAcgASgDEg8KB3NlZWtfdHMYCCABKAMSDQoFZXh0cmEYCSABKAkiPAoQTGl2ZVN0YXR1c05vdGlmeRIOCgZzdGF0dXMYASABKAMSCwoDbXNnGAIgASgJEgsKA2NpZBgDIAEoAyIcCg1Fc3BvcnRzTm90aWZ5EgsKA2NpZBgBIAEoAyJICg9QdWJsaWNpdHlOb3RpZnkSFAoMcHVibGljaXR5X2lkGAEgASgDEg8KB3Jvb21faWQYAiABKAMSDgoGc3RhdHVzGAMgASgDIiEKDkxpdmVTa2lwTm90aWZ5Eg8KB2xpdmVfaWQYASABKAMyqAMKAlR2EkoKBFByb2oSFi5nb29nbGUucHJvdG9idWYuRW1wdHkaKC5iaWxpYmlsaS5icm9hZGNhc3QubWVzc2FnZS50di5Qcm9qUmVwbHkwARJXCgpMaXZlU3RhdHVzEhYuZ29vZ2xlLnByb3RvYnVmLkVtcHR5Gi8uYmlsaWJpbGkuYnJvYWRjYXN0Lm1lc3NhZ2UudHYuTGl2ZVN0YXR1c05vdGlmeTABElEKB0VzcG9ydHMSFi5nb29nbGUucHJvdG9idWYuRW1wdHkaLC5iaWxpYmlsaS5icm9hZGNhc3QubWVzc2FnZS50di5Fc3BvcnRzTm90aWZ5MAESVQoJUHVibGljaXR5EhYuZ29vZ2xlLnByb3RvYnVmLkVtcHR5Gi4uYmlsaWJpbGkuYnJvYWRjYXN0Lm1lc3NhZ2UudHYuUHVibGljaXR5Tm90aWZ5MAESUwoITGl2ZVNraXASFi5nb29nbGUucHJvdG9idWYuRW1wdHkaLS5iaWxpYmlsaS5icm9hZGNhc3QubWVzc2FnZS50di5MaXZlU2tpcE5vdGlmeTABYgZwcm90bzM", [file_google_protobuf_empty]);

/**
 * 投屏
 *
 * @generated from message bilibili.broadcast.message.tv.ProjReply
 */
export type ProjReply = Message<"bilibili.broadcast.message.tv.ProjReply"> & {
  /**
   * 投屏命令
   * 1:起播 2:快进 3:快退 4:seek播放进度 5:暂停 6:暂停恢复
   *
   * @generated from field: int64 cmd_type = 1;
   */
  cmdType: bigint;

  /**
   * 用户id
   *
   * @generated from field: int64 mid = 2;
   */
  mid: bigint;

  /**
   * 稿件id
   *
   * @generated from field: int64 aid = 3;
   */
  aid: bigint;

  /**
   * 视频id
   *
   * @generated from field: int64 cid = 4;
   */
  cid: bigint;

  /**
   * 视频类型
   * 0:ugc 1:pgc 2:pugv
   *
   * @generated from field: int64 video_type = 5;
   */
  videoType: bigint;

  /**
   * 单集id，pgc和pugv需要传
   *
   * @generated from field: int64 ep_id = 6;
   */
  epId: bigint;

  /**
   * 剧集id
   *
   * @generated from field: int64 season_id = 7;
   */
  seasonId: bigint;

  /**
   * seek 的位置，cmd位seek时有值，单位秒
   *
   * @generated from field: int64 seek_ts = 8;
   */
  seekTs: bigint;

  /**
   * 其他指令对应内容
   *
   * @generated from field: string extra = 9;
   */
  extra: string;
};

/**
 * Describes the message bilibili.broadcast.message.tv.ProjReply.
 * Use `create(ProjReplySchema)` to create a new message.
 */
export const ProjReplySchema: GenMessage<ProjReply> = /*@__PURE__*/
  messageDesc(file_bilibili_broadcast_message_tv_proj, 0);

/**
 * 直播状态
 *
 * @generated from message bilibili.broadcast.message.tv.LiveStatusNotify
 */
export type LiveStatusNotify = Message<"bilibili.broadcast.message.tv.LiveStatusNotify"> & {
  /**
   * 直播状态
   * 1:开播 2:关播 3:截流 4:截流恢复
   *
   * @generated from field: int64 status = 1;
   */
  status: bigint;

  /**
   * 文案
   *
   * @generated from field: string msg = 2;
   */
  msg: string;

  /**
   * 直播房间号
   *
   * @generated from field: int64 cid = 3;
   */
  cid: bigint;
};

/**
 * Describes the message bilibili.broadcast.message.tv.LiveStatusNotify.
 * Use `create(LiveStatusNotifySchema)` to create a new message.
 */
export const LiveStatusNotifySchema: GenMessage<LiveStatusNotify> = /*@__PURE__*/
  messageDesc(file_bilibili_broadcast_message_tv_proj, 1);

/**
 * @generated from message bilibili.broadcast.message.tv.EsportsNotify
 */
export type EsportsNotify = Message<"bilibili.broadcast.message.tv.EsportsNotify"> & {
  /**
   * 直播房间号
   *
   * @generated from field: int64 cid = 1;
   */
  cid: bigint;
};

/**
 * Describes the message bilibili.broadcast.message.tv.EsportsNotify.
 * Use `create(EsportsNotifySchema)` to create a new message.
 */
export const EsportsNotifySchema: GenMessage<EsportsNotify> = /*@__PURE__*/
  messageDesc(file_bilibili_broadcast_message_tv_proj, 2);

/**
 * 直播插卡
 *
 * @generated from message bilibili.broadcast.message.tv.PublicityNotify
 */
export type PublicityNotify = Message<"bilibili.broadcast.message.tv.PublicityNotify"> & {
  /**
   * 插卡id
   *
   * @generated from field: int64 publicity_id = 1;
   */
  publicityId: bigint;

  /**
   * 直播房间号
   *
   * @generated from field: int64 room_id = 2;
   */
  roomId: bigint;

  /**
   * 直播间状态
   * 0:未开播 1:直播中 2:轮播中
   *
   * @generated from field: int64 status = 3;
   */
  status: bigint;
};

/**
 * Describes the message bilibili.broadcast.message.tv.PublicityNotify.
 * Use `create(PublicityNotifySchema)` to create a new message.
 */
export const PublicityNotifySchema: GenMessage<PublicityNotify> = /*@__PURE__*/
  messageDesc(file_bilibili_broadcast_message_tv_proj, 3);

/**
 * 直转点
 *
 * @generated from message bilibili.broadcast.message.tv.LiveSkipNotify
 */
export type LiveSkipNotify = Message<"bilibili.broadcast.message.tv.LiveSkipNotify"> & {
  /**
   * 直播id
   *
   * @generated from field: int64 live_id = 1;
   */
  liveId: bigint;
};

/**
 * Describes the message bilibili.broadcast.message.tv.LiveSkipNotify.
 * Use `create(LiveSkipNotifySchema)` to create a new message.
 */
export const LiveSkipNotifySchema: GenMessage<LiveSkipNotify> = /*@__PURE__*/
  messageDesc(file_bilibili_broadcast_message_tv_proj, 4);

/**
 * @generated from service bilibili.broadcast.message.tv.Tv
 */
export const Tv: GenService<{
  /**
   * 投屏
   *
   * @generated from rpc bilibili.broadcast.message.tv.Tv.Proj
   */
  proj: {
    methodKind: "server_streaming";
    input: typeof EmptySchema;
    output: typeof ProjReplySchema;
  },
  /**
   * 直播状态
   *
   * @generated from rpc bilibili.broadcast.message.tv.Tv.LiveStatus
   */
  liveStatus: {
    methodKind: "server_streaming";
    input: typeof EmptySchema;
    output: typeof LiveStatusNotifySchema;
  },
  /**
   * 赛事比分通知
   *
   * @generated from rpc bilibili.broadcast.message.tv.Tv.Esports
   */
  esports: {
    methodKind: "server_streaming";
    input: typeof EmptySchema;
    output: typeof EsportsNotifySchema;
  },
  /**
   * 直播插卡
   *
   * @generated from rpc bilibili.broadcast.message.tv.Tv.Publicity
   */
  publicity: {
    methodKind: "server_streaming";
    input: typeof EmptySchema;
    output: typeof PublicityNotifySchema;
  },
  /**
   * 直转点
   *
   * @generated from rpc bilibili.broadcast.message.tv.Tv.LiveSkip
   */
  liveSkip: {
    methodKind: "server_streaming";
    input: typeof EmptySchema;
    output: typeof LiveSkipNotifySchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_bilibili_broadcast_message_tv_proj, 0);

