// @generated by protoc-gen-es v2.14.1 with parameter "target=ts"
// @generated from file bilibili/app/show/region/v1/region.proto (package bilibili.app.show.region.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file bilibili/app/show/region/v1/region.proto.
 */
export const file_bilibili_app_show_region_v1_region: GenFile = /*@__PURE__*/
  fileDesc("CihiaWxpYmlsaS9hcHAvc2hvdy9yZWdpb24vdjEvcmVnaW9uLnByb3RvEhtiaWxpYmlsaS5hcHAuc2hvdy5yZWdpb24udjEiOAoMUmVnaW9uQ29uZmlnEhMKC3NjZW5lc19uYW1lGAEgASgJEhMKC3NjZW5lc190eXBlGAIgASgJIoUCCgpSZWdpb25JbmZvEgsKA3RpZBgBIAEoBRIMCgRyZWlkGAIgASgFEgwKBG5hbWUYAyABKAkSDAoEbG9nbxgEIAEoCRIMCgRnb3RvGAUgASgJEg0KBXBhcmFtGAYgASgJEgsKA3VyaRgHIAEoCRIMCgR0eXBlGAggASgFEhIKCmlzX2Jhbmd1bWkYCSABKAUSOQoIY2hpbGRyZW4YCiADKAsyJy5iaWxpYmlsaS5hcHAuc2hvdy5yZWdpb24udjEuUmVnaW9uSW5mbxI5CgZjb25maWcYCyADKAsyKS5iaWxpYmlsaS5hcHAuc2hvdy5yZWdpb24udjEuUmVnaW9uQ29uZmlnIkcKC1JlZ2lvblJlcGx5EjgKB3JlZ2lvbnMYASADKAsyJy5iaWxpYmlsaS5hcHAuc2hvdy5yZWdpb24udjEuUmVnaW9uSW5mbyIZCglSZWdpb25SZXESDAoEbGFuZxgBIAEoCTJkCgZSZWdpb24SWgoGUmVnaW9uEiYuYmlsaWJpbGkuYXBwLnNob3cucmVnaW9uLnYxLlJlZ2lvblJlcRooLmJpbGliaWxpLmFwcC5zaG93LnJlZ2lvbi52MS5SZWdpb25SZXBseWIGcHJvdG8z");

/**
 * @generated from message bilibili.app.show.region.v1.RegionConfig
 */
export type RegionConfig = Message<"bilibili.app.show.region.v1.RegionConfig"> & {
  /**
   * @generated from field: string scenes_name = 1;
   */
  scenesName: string;

  /**
   * @generated from field: string scenes_type = 2;
   */
  scenesType: string;
};

/**
 * Describes the message bilibili.app.show.region.v1.RegionConfig.
 * Use `create(RegionConfigSchema)` to create a new message.
 */
export const RegionConfigSchema: GenMessage<RegionConfig> = /*@__PURE__*/
  messageDesc(file_bilibili_app_show_region_v1_region, 0);

/**
 * @generated from message bilibili.app.show.region.v1.RegionInfo
 */
export type RegionInfo = Message<"bilibili.app.show.region.v1.RegionInfo"> & {
  /**
   * @generated from field: int32 tid = 1;
   */
  tid: number;

  /**
   * @generated from field: int32 reid = 2;
   */
  reid: number;

  /**
   * @generated from field: string name = 3;
   */
  name: string;

  /**
   * @generated from field: string logo = 4;
   */
  logo: string;

  /**
   * @generated from field: string goto = 5;
   */
  goto: string;

  /**
   * @generated from field: string param = 6;
   */
  param: string;

  /**
   * @generated from field: string uri = 7;
   */
  uri: string;

  /**
   * @generated from field: int32 type = 8;
   */
  type: number;

  /**
   * @generated from field: int32 is_bangumi = 9;
   */
  isBangumi: number;

  /**
   * @generated from field: repeated bilibili.app.show.region.v1.RegionInfo children = 10;
   */
  children: RegionInfo[];

  /**
   * @generated from field: repeated bilibili.app.show.region.v1.RegionConfig config = 11;
   */
  config: RegionConfig[];
};

/**
 * Describes the message bilibili.app.show.region.v1.RegionInfo.
 * Use `create(RegionInfoSchema)` to create a new message.
 */
export const RegionInfoSchema: GenMessage<RegionInfo> = /*@__PURE__*/
  messageDesc(file_bilibili_app_show_region_v1_region, 1);

/**
 * @generated from message bilibili.app.show.region.v1.RegionReply
 */
export type RegionReply = Message<"bilibili.app.show.region.v1.RegionReply"> & {
  /**
   * @generated from field: repeated bilibili.app.show.region.v1.RegionInfo regions = 1;
   */
  regions: RegionInfo[];
};

/**
 * Describes the message bilibili.app.show.region.v1.RegionReply.
 * Use `create(RegionReplySchema)` to create a new message.
 */
export const RegionReplySchema: GenMessage<RegionReply> = /*@__PURE__*/
  messageDesc(file_bilibili_app_show_region_v1_region, 2);

/**
 * @generated from message bilibili.app.show.region.v1.RegionReq
 */
export type RegionReq = Message<"bilibili.app.show.region.v1.RegionReq"> & {
  /**
   * @generated from field: string lang = 1;
   */
  lang: string;
};

/**
 * Describes the message bilibili.app.show.region.v1.RegionReq.
 * Use `create(RegionReqSchema)` to create a new message.
 */
export const RegionReqSchema: GenMessage<RegionReq> = /*@__PURE__*/
  messageDesc(file_bilibili_app_show_region_v1_region, 3);

/**
 * @generated from service bilibili.app.show.region.v1.Region
 */
export const Region: GenService<{
  /**
   * @generated from rpc bilibili.app.show.region.v1.Region.Region
   */
  region: {
    methodKind: "unary";
    input: typeof RegionReqSchema;
    output: typeof RegionReplySchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_bilibili_app_show_region_v1_region, 0);

