require File.join(File.dirname(`node --print "require.resolve('expo/package.json')"`), "scripts/autolinking")
# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

# use cocoapods CDN per https://blog.cocoapods.org/CocoaPods-1.7.2/
source 'https://cdn.cocoapods.org/'

platform :ios, '13.4'
prepare_react_native_project!
linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'azusa-player-mobile' do
  # https://github.com/arthenica/ffmpeg-kit/tree/main/react-native#222-enabling-a-package-on-ios
  pod 'ffmpeg-kit-react-native', :subspecs => ['audio'], :podspec => '../node_modules/ffmpeg-kit-react-native/ffmpeg-kit-react-native.podspec'

  config = use_native_modules!
  # for svga-player
  pod 'Protobuf', '= 3.22.1'
  
  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'APMTests' do
    inherit! :complete
    use_react_native!
    # Pods for testing
  end

  post_install do |installer|
  # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
  react_native_post_install(
      installer,
      # Set `mac_catalyst_enabled` to `true` in order to apply patches
      # necessary for Mac Catalyst builds
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )

    # only fails in command line!!! ok with xcode GUI!
    # https://github.com/facebook/react-native/issues/29709
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.4'
      end
      if target.name == "React-Core.common-AccessibilityResources"
        target.remove_from_project
      end
      if target.name == "React-Core.common-RCTI18nStrings"
        target.remove_from_project
      end
    end
  end
end

# https://github.com/expo/expo/issues/15959
# though also https://github.com/facebook/react-native/issues/35664
# which is temp fixed by https://github.com/facebook/react-native/issues/35664#issuecomment-1590189067
# RN 0.72 fixes this?
use_expo_modules!

post_integrate do |installer|
  begin
    expo_patch_react_imports!(installer)
  rescue => e
    Pod::UI.warn e
  end
end