// @generated by protoc-gen-es v2.14.1 with parameter "target=ts"
// @generated from file bilibili/app/archive/middleware/v1/preload.proto (package bilibili.app.archive.middleware.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file bilibili/app/archive/middleware/v1/preload.proto.
 */
export const file_bilibili_app_archive_middleware_v1_preload: GenFile = /*@__PURE__*/
  fileDesc("CjBiaWxpYmlsaS9hcHAvYXJjaGl2ZS9taWRkbGV3YXJlL3YxL3ByZWxvYWQucHJvdG8SImJpbGliaWxpLmFwcC5hcmNoaXZlLm1pZGRsZXdhcmUudjEiYQoKUGxheWVyQXJncxIKCgJxbhgBIAEoAxINCgVmbnZlchgCIAEoAxINCgVmbnZhbBgDIAEoAxISCgpmb3JjZV9ob3N0GAQgASgDEhUKDXZvaWNlX2JhbGFuY2UYBSABKANiBnByb3RvMw");

/**
 * 视频秒开参数
 *
 * @generated from message bilibili.app.archive.middleware.v1.PlayerArgs
 */
export type PlayerArgs = Message<"bilibili.app.archive.middleware.v1.PlayerArgs"> & {
  /**
   * 清晰度
   *
   * @generated from field: int64 qn = 1;
   */
  qn: bigint;

  /**
   * 流版本
   *
   * @generated from field: int64 fnver = 2;
   */
  fnver: bigint;

  /**
   * 流类型
   *
   * @generated from field: int64 fnval = 3;
   */
  fnval: bigint;

  /**
   * 返回url是否强制使用域名
   * 0:不强制使用域名 1:http域名 2:https域名
   *
   * @generated from field: int64 force_host = 4;
   */
  forceHost: bigint;

  /**
   * 音量均衡
   *
   * @generated from field: int64 voice_balance = 5;
   */
  voiceBalance: bigint;
};

/**
 * Describes the message bilibili.app.archive.middleware.v1.PlayerArgs.
 * Use `create(PlayerArgsSchema)` to create a new message.
 */
export const PlayerArgsSchema: GenMessage<PlayerArgs> = /*@__PURE__*/
  messageDesc(file_bilibili_app_archive_middleware_v1_preload, 0);

