// @generated by protoc-gen-es v2.14.1 with parameter "target=ts"
// @generated from file bilibili/main/common/arch/doll/v1/doll.proto (package bilibili.main.common.arch.doll.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file bilibili/main/common/arch/doll/v1/doll.proto.
 */
export const file_bilibili_main_common_arch_doll_v1_doll: GenFile = /*@__PURE__*/
  fileDesc("CixiaWxpYmlsaS9tYWluL2NvbW1vbi9hcmNoL2RvbGwvdjEvZG9sbC5wcm90bxIhYmlsaWJpbGkubWFpbi5jb21tb24uYXJjaC5kb2xsLnYxIjoKDEVycm9yUmVxdWVzdBINCgVlcnJvchgCIAEoBRIMCgR0aW1lGAEgASgDEg0KBWRlbGF5GAMgASgDIisKDUVycm9yUmVzcG9uc2USDAoEaG9zdBgBIAEoCRIMCgR0aW1lGAMgASgDIhsKC1BpbmdSZXF1ZXN0EgwKBHRpbWUYASABKAMiKgoMUGluZ1Jlc3BvbnNlEgwKBGhvc3QYASABKAkSDAoEdGltZRgDIAEoAyIdCgpTYXlSZXF1ZXN0Eg8KB2NvbnRlbnQYASABKAkiOgoLU2F5UmVzcG9uc2USDAoEaG9zdBgBIAEoCRIPCgdjb250ZW50GAIgASgJEgwKBHRpbWUYAyABKAMywQIKBEVjaG8SZwoEUGluZxIuLmJpbGliaWxpLm1haW4uY29tbW9uLmFyY2guZG9sbC52MS5QaW5nUmVxdWVzdBovLmJpbGliaWxpLm1haW4uY29tbW9uLmFyY2guZG9sbC52MS5QaW5nUmVzcG9uc2USZAoDU2F5Ei0uYmlsaWJpbGkubWFpbi5jb21tb24uYXJjaC5kb2xsLnYxLlNheVJlcXVlc3QaLi5iaWxpYmlsaS5tYWluLmNvbW1vbi5hcmNoLmRvbGwudjEuU2F5UmVzcG9uc2USagoFRXJyb3ISLy5iaWxpYmlsaS5tYWluLmNvbW1vbi5hcmNoLmRvbGwudjEuRXJyb3JSZXF1ZXN0GjAuYmlsaWJpbGkubWFpbi5jb21tb24uYXJjaC5kb2xsLnYxLkVycm9yUmVzcG9uc2ViBnByb3RvMw");

/**
 * @generated from message bilibili.main.common.arch.doll.v1.ErrorRequest
 */
export type ErrorRequest = Message<"bilibili.main.common.arch.doll.v1.ErrorRequest"> & {
  /**
   * @generated from field: int32 error = 2;
   */
  error: number;

  /**
   * @generated from field: int64 time = 1;
   */
  time: bigint;

  /**
   * @generated from field: int64 delay = 3;
   */
  delay: bigint;
};

/**
 * Describes the message bilibili.main.common.arch.doll.v1.ErrorRequest.
 * Use `create(ErrorRequestSchema)` to create a new message.
 */
export const ErrorRequestSchema: GenMessage<ErrorRequest> = /*@__PURE__*/
  messageDesc(file_bilibili_main_common_arch_doll_v1_doll, 0);

/**
 * @generated from message bilibili.main.common.arch.doll.v1.ErrorResponse
 */
export type ErrorResponse = Message<"bilibili.main.common.arch.doll.v1.ErrorResponse"> & {
  /**
   * @generated from field: string host = 1;
   */
  host: string;

  /**
   * @generated from field: int64 time = 3;
   */
  time: bigint;
};

/**
 * Describes the message bilibili.main.common.arch.doll.v1.ErrorResponse.
 * Use `create(ErrorResponseSchema)` to create a new message.
 */
export const ErrorResponseSchema: GenMessage<ErrorResponse> = /*@__PURE__*/
  messageDesc(file_bilibili_main_common_arch_doll_v1_doll, 1);

/**
 * @generated from message bilibili.main.common.arch.doll.v1.PingRequest
 */
export type PingRequest = Message<"bilibili.main.common.arch.doll.v1.PingRequest"> & {
  /**
   * @generated from field: int64 time = 1;
   */
  time: bigint;
};

/**
 * Describes the message bilibili.main.common.arch.doll.v1.PingRequest.
 * Use `create(PingRequestSchema)` to create a new message.
 */
export const PingRequestSchema: GenMessage<PingRequest> = /*@__PURE__*/
  messageDesc(file_bilibili_main_common_arch_doll_v1_doll, 2);

/**
 * @generated from message bilibili.main.common.arch.doll.v1.PingResponse
 */
export type PingResponse = Message<"bilibili.main.common.arch.doll.v1.PingResponse"> & {
  /**
   * @generated from field: string host = 1;
   */
  host: string;

  /**
   * @generated from field: int64 time = 3;
   */
  time: bigint;
};

/**
 * Describes the message bilibili.main.common.arch.doll.v1.PingResponse.
 * Use `create(PingResponseSchema)` to create a new message.
 */
export const PingResponseSchema: GenMessage<PingResponse> = /*@__PURE__*/
  messageDesc(file_bilibili_main_common_arch_doll_v1_doll, 3);

/**
 * @generated from message bilibili.main.common.arch.doll.v1.SayRequest
 */
export type SayRequest = Message<"bilibili.main.common.arch.doll.v1.SayRequest"> & {
  /**
   * @generated from field: string content = 1;
   */
  content: string;
};

/**
 * Describes the message bilibili.main.common.arch.doll.v1.SayRequest.
 * Use `create(SayRequestSchema)` to create a new message.
 */
export const SayRequestSchema: GenMessage<SayRequest> = /*@__PURE__*/
  messageDesc(file_bilibili_main_common_arch_doll_v1_doll, 4);

/**
 * @generated from message bilibili.main.common.arch.doll.v1.SayResponse
 */
export type SayResponse = Message<"bilibili.main.common.arch.doll.v1.SayResponse"> & {
  /**
   * @generated from field: string host = 1;
   */
  host: string;

  /**
   * @generated from field: string content = 2;
   */
  content: string;

  /**
   * @generated from field: int64 time = 3;
   */
  time: bigint;
};

/**
 * Describes the message bilibili.main.common.arch.doll.v1.SayResponse.
 * Use `create(SayResponseSchema)` to create a new message.
 */
export const SayResponseSchema: GenMessage<SayResponse> = /*@__PURE__*/
  messageDesc(file_bilibili_main_common_arch_doll_v1_doll, 5);

/**
 * @generated from service bilibili.main.common.arch.doll.v1.Echo
 */
export const Echo: GenService<{
  /**
   * @generated from rpc bilibili.main.common.arch.doll.v1.Echo.Ping
   */
  ping: {
    methodKind: "unary";
    input: typeof PingRequestSchema;
    output: typeof PingResponseSchema;
  },
  /**
   * @generated from rpc bilibili.main.common.arch.doll.v1.Echo.Say
   */
  say: {
    methodKind: "unary";
    input: typeof SayRequestSchema;
    output: typeof SayResponseSchema;
  },
  /**
   * @generated from rpc bilibili.main.common.arch.doll.v1.Echo.Error
   */
  error: {
    methodKind: "unary";
    input: typeof ErrorRequestSchema;
    output: typeof ErrorResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_bilibili_main_common_arch_doll_v1_doll, 0);

