// @generated by protoc-gen-es v2.14.1 with parameter "target=ts"
// @generated from file bilibili/app/dynamic/v2/campus.proto (package bilibili.app.dynamic.v2, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { PlayerArgs } from "../../archive/middleware/v1/preload_pb";
import { file_bilibili_app_archive_middleware_v1_preload } from "../../archive/middleware/v1/preload_pb";
import type { FeedPaginationReply } from "../../../pagination/pagination_pb";
import { file_bilibili_pagination_pagination } from "../../../pagination/pagination_pb";
import type { ItemWHRatio } from "../common/dynamic_pb";
import { file_bilibili_app_dynamic_common_dynamic } from "../common/dynamic_pb";
import type { CampusRcmdReqFrom, CoverIconWithText, RcmdReason } from "./dynamic_pb";
import { file_bilibili_app_dynamic_v2_dynamic } from "./dynamic_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file bilibili/app/dynamic/v2/campus.proto.
 */
export const file_bilibili_app_dynamic_v2_campus: GenFile = /*@__PURE__*/
  fileDesc("CiRiaWxpYmlsaS9hcHAvZHluYW1pYy92Mi9jYW1wdXMucHJvdG8SF2JpbGliaWxpLmFwcC5keW5hbWljLnYyIqwBChNDYW1wdXNXYXRlckZsb3dJdGVtEhEKCWl0ZW1fdHlwZRgBIAEoBRI6Cgh3aF9yYXRpbxgCIAEoCzIoLmJpbGliaWxpLmFwcC5keW5hbWljLmNvbW1vbi5JdGVtV0hSYXRpbxI+CgxpdGVtX2RlZmF1bHQYAyABKAsyJi5iaWxpYmlsaS5hcHAuZHluYW1pYy52Mi5XRkl0ZW1EZWZhdWx0SABCBgoEaXRlbSKyAQoQV2F0ZXJGbG93UmNtZFJlcRIRCgljYW1wdXNfaWQYASABKAMSDAoEcGFnZRgCIAEoBRJDCgtwbGF5ZXJfYXJncxgDIAEoCzIuLmJpbGliaWxpLmFwcC5hcmNoaXZlLm1pZGRsZXdhcmUudjEuUGxheWVyQXJncxI4CgRmcm9tGAQgASgOMiouYmlsaWJpbGkuYXBwLmR5bmFtaWMudjIuQ2FtcHVzUmNtZFJlcUZyb20iigEKEVdhdGVyRmxvd1JjbWRSZXNwEjsKBWl0ZW1zGAEgAygLMiwuYmlsaWJpbGkuYXBwLmR5bmFtaWMudjIuQ2FtcHVzV2F0ZXJGbG93SXRlbRI4CgZvZmZzZXQYAiABKAsyKC5iaWxpYmlsaS5wYWdpbmF0aW9uLkZlZWRQYWdpbmF0aW9uUmVwbHkiwAMKDVdGSXRlbURlZmF1bHQSDQoFdGl0bGUYASABKAkSDQoFY292ZXIYAiABKAkSQQoNYm90dG9tX2xlZnRfMRgDIAEoCzIqLmJpbGliaWxpLmFwcC5keW5hbWljLnYyLkNvdmVySWNvbldpdGhUZXh0EkEKDWJvdHRvbV9sZWZ0XzIYBCABKAsyKi5iaWxpYmlsaS5hcHAuZHluYW1pYy52Mi5Db3Zlckljb25XaXRoVGV4dBJCCg5ib3R0b21fcmlnaHRfMRgFIAEoCzIqLmJpbGliaWxpLmFwcC5keW5hbWljLnYyLkNvdmVySWNvbldpdGhUZXh0EgsKA3VyaRgGIAEoCRI4CgtyY21kX3JlYXNvbhgHIAEoCzIjLmJpbGliaWxpLmFwcC5keW5hbWljLnYyLlJjbWRSZWFzb24STAoLYW5ub3RhdGlvbnMYCCADKAsyNy5iaWxpYmlsaS5hcHAuZHluYW1pYy52Mi5XRkl0ZW1EZWZhdWx0LkFubm90YXRpb25zRW50cnkaMgoQQW5ub3RhdGlvbnNFbnRyeRILCgNrZXkYASABKAkSDQoFdmFsdWUYAiABKAk6AjgBMnAKBkNhbXB1cxJmCg1XYXRlckZsb3dSY21kEikuYmlsaWJpbGkuYXBwLmR5bmFtaWMudjIuV2F0ZXJGbG93UmNtZFJlcRoqLmJpbGliaWxpLmFwcC5keW5hbWljLnYyLldhdGVyRmxvd1JjbWRSZXNwYgZwcm90bzM", [file_bilibili_app_archive_middleware_v1_preload, file_bilibili_pagination_pagination, file_bilibili_app_dynamic_common_dynamic, file_bilibili_app_dynamic_v2_dynamic]);

/**
 *
 *
 * @generated from message bilibili.app.dynamic.v2.CampusWaterFlowItem
 */
export type CampusWaterFlowItem = Message<"bilibili.app.dynamic.v2.CampusWaterFlowItem"> & {
  /**
   *
   *
   * @generated from field: int32 item_type = 1;
   */
  itemType: number;

  /**
   *
   *
   * @generated from field: bilibili.app.dynamic.common.ItemWHRatio wh_ratio = 2;
   */
  whRatio?: ItemWHRatio | undefined;

  /**
   *
   *
   * @generated from oneof bilibili.app.dynamic.v2.CampusWaterFlowItem.item
   */
  item: {
    /**
     * @generated from field: bilibili.app.dynamic.v2.WFItemDefault item_default = 3;
     */
    value: WFItemDefault;
    case: "itemDefault";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message bilibili.app.dynamic.v2.CampusWaterFlowItem.
 * Use `create(CampusWaterFlowItemSchema)` to create a new message.
 */
export const CampusWaterFlowItemSchema: GenMessage<CampusWaterFlowItem> = /*@__PURE__*/
  messageDesc(file_bilibili_app_dynamic_v2_campus, 0);

/**
 *
 *
 * @generated from message bilibili.app.dynamic.v2.WaterFlowRcmdReq
 */
export type WaterFlowRcmdReq = Message<"bilibili.app.dynamic.v2.WaterFlowRcmdReq"> & {
  /**
   *
   *
   * @generated from field: int64 campus_id = 1;
   */
  campusId: bigint;

  /**
   *
   *
   * @generated from field: int32 page = 2;
   */
  page: number;

  /**
   *
   *
   * @generated from field: bilibili.app.archive.middleware.v1.PlayerArgs player_args = 3;
   */
  playerArgs?: PlayerArgs | undefined;

  /**
   *
   *
   * @generated from field: bilibili.app.dynamic.v2.CampusRcmdReqFrom from = 4;
   */
  from: CampusRcmdReqFrom;
};

/**
 * Describes the message bilibili.app.dynamic.v2.WaterFlowRcmdReq.
 * Use `create(WaterFlowRcmdReqSchema)` to create a new message.
 */
export const WaterFlowRcmdReqSchema: GenMessage<WaterFlowRcmdReq> = /*@__PURE__*/
  messageDesc(file_bilibili_app_dynamic_v2_campus, 1);

/**
 *
 *
 * @generated from message bilibili.app.dynamic.v2.WaterFlowRcmdResp
 */
export type WaterFlowRcmdResp = Message<"bilibili.app.dynamic.v2.WaterFlowRcmdResp"> & {
  /**
   *
   *
   * @generated from field: repeated bilibili.app.dynamic.v2.CampusWaterFlowItem items = 1;
   */
  items: CampusWaterFlowItem[];

  /**
   *
   *
   * @generated from field: bilibili.pagination.FeedPaginationReply offset = 2;
   */
  offset?: FeedPaginationReply | undefined;
};

/**
 * Describes the message bilibili.app.dynamic.v2.WaterFlowRcmdResp.
 * Use `create(WaterFlowRcmdRespSchema)` to create a new message.
 */
export const WaterFlowRcmdRespSchema: GenMessage<WaterFlowRcmdResp> = /*@__PURE__*/
  messageDesc(file_bilibili_app_dynamic_v2_campus, 2);

/**
 *
 *
 * @generated from message bilibili.app.dynamic.v2.WFItemDefault
 */
export type WFItemDefault = Message<"bilibili.app.dynamic.v2.WFItemDefault"> & {
  /**
   *
   *
   * @generated from field: string title = 1;
   */
  title: string;

  /**
   *
   *
   * @generated from field: string cover = 2;
   */
  cover: string;

  /**
   *
   *
   * @generated from field: bilibili.app.dynamic.v2.CoverIconWithText bottom_left_1 = 3;
   */
  bottomLeft1?: CoverIconWithText | undefined;

  /**
   *
   *
   * @generated from field: bilibili.app.dynamic.v2.CoverIconWithText bottom_left_2 = 4;
   */
  bottomLeft2?: CoverIconWithText | undefined;

  /**
   *
   *
   * @generated from field: bilibili.app.dynamic.v2.CoverIconWithText bottom_right_1 = 5;
   */
  bottomRight1?: CoverIconWithText | undefined;

  /**
   *
   *
   * @generated from field: string uri = 6;
   */
  uri: string;

  /**
   *
   *
   * @generated from field: bilibili.app.dynamic.v2.RcmdReason rcmd_reason = 7;
   */
  rcmdReason?: RcmdReason | undefined;

  /**
   *
   *
   * @generated from field: map<string, string> annotations = 8;
   */
  annotations: { [key: string]: string };
};

/**
 * Describes the message bilibili.app.dynamic.v2.WFItemDefault.
 * Use `create(WFItemDefaultSchema)` to create a new message.
 */
export const WFItemDefaultSchema: GenMessage<WFItemDefault> = /*@__PURE__*/
  messageDesc(file_bilibili_app_dynamic_v2_campus, 3);

/**
 * @generated from service bilibili.app.dynamic.v2.Campus
 */
export const Campus: GenService<{
  /**
   *
   *
   * @generated from rpc bilibili.app.dynamic.v2.Campus.WaterFlowRcmd
   */
  waterFlowRcmd: {
    methodKind: "unary";
    input: typeof WaterFlowRcmdReqSchema;
    output: typeof WaterFlowRcmdRespSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_bilibili_app_dynamic_v2_campus, 0);

