// @generated by protoc-gen-es v2.14.1 with parameter "target=ts"
// @generated from file bilibili/broadcast/message/esports/notify.proto (package bilibili.broadcast.message.esports, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file bilibili/broadcast/message/esports/notify.proto.
 */
export const file_bilibili_broadcast_message_esports_notify: GenFile = /*@__PURE__*/
  fileDesc("Ci9iaWxpYmlsaS9icm9hZGNhc3QvbWVzc2FnZS9lc3BvcnRzL25vdGlmeS5wcm90bxIiYmlsaWJpbGkuYnJvYWRjYXN0Lm1lc3NhZ2UuZXNwb3J0cyIVCgZOb3RpZnkSCwoDY2lkGAEgASgDYgZwcm90bzM");

/**
 * @generated from message bilibili.broadcast.message.esports.Notify
 */
export type Notify = Message<"bilibili.broadcast.message.esports.Notify"> & {
  /**
   * cid
   *
   * @generated from field: int64 cid = 1;
   */
  cid: bigint;
};

/**
 * Describes the message bilibili.broadcast.message.esports.Notify.
 * Use `create(NotifySchema)` to create a new message.
 */
export const NotifySchema: GenMessage<Notify> = /*@__PURE__*/
  messageDesc(file_bilibili_broadcast_message_esports_notify, 0);

