// @generated by protoc-gen-es v2.14.1 with parameter "target=ts"
// @generated from file bilibili/api/player/v1/player.proto (package bilibili.api.player.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file bilibili/api/player/v1/player.proto.
 */
export const file_bilibili_api_player_v1_player: GenFile = /*@__PURE__*/
  fileDesc("CiNiaWxpYmlsaS9hcGkvcGxheWVyL3YxL3BsYXllci5wcm90bxIWYmlsaWJpbGkuYXBpLnBsYXllci52MSIcCg5IZWFydGJlYXRSZXBseRIKCgJ0cxgBIAEoAyK4BAoMSGVhcnRiZWF0UmVxEhMKC3NlcnZlcl90aW1lGAEgASgDEg8KB3Nlc3Npb24YAiABKAkSCwoDbWlkGAMgASgDEgsKA2FpZBgEIAEoAxILCgNjaWQYBSABKAMSCwoDc2lkGAYgASgJEgwKBGVwaWQYByABKAMSDAoEdHlwZRgIIAEoCRIQCghzdWJfdHlwZRgJIAEoBRIPCgdxdWFsaXR5GAogASgFEhIKCnRvdGFsX3RpbWUYCyABKAMSEwoLcGF1c2VkX3RpbWUYDCABKAMSEwoLcGxheWVkX3RpbWUYDSABKAMSFgoOdmlkZW9fZHVyYXRpb24YDiABKAMSEQoJcGxheV90eXBlGA8gASgJEhQKDG5ldHdvcmtfdHlwZRgQIAEoBRIfChdsYXN0X3BsYXlfcHJvZ3Jlc3NfdGltZRgRIAEoAxIeChZtYXhfcGxheV9wcm9ncmVzc190aW1lGBIgASgDEgwKBGZyb20YEyABKAUSEgoKZnJvbV9zcG1pZBgUIAEoCRINCgVzcG1pZBgVIAEoCRITCgtlcGlkX3N0YXR1cxgWIAEoCRITCgtwbGF5X3N0YXR1cxgXIAEoCRITCgt1c2VyX3N0YXR1cxgYIAEoCRIaChJhY3R1YWxfcGxheWVkX3RpbWUYGSABKAMSEQoJYXV0b19wbGF5GBogASgFEhYKDmxpc3RfcGxheV90aW1lGBsgASgDEhgKEGRldGFpbF9wbGF5X3RpbWUYHCABKAMyYwoJSGVhcnRiZWF0ElYKBk1vYmlsZRIkLmJpbGliaWxpLmFwaS5wbGF5ZXIudjEuSGVhcnRiZWF0UmVxGiYuYmlsaWJpbGkuYXBpLnBsYXllci52MS5IZWFydGJlYXRSZXBseWIGcHJvdG8z");

/**
 * 客户端心跳上报-响应
 *
 * @generated from message bilibili.api.player.v1.HeartbeatReply
 */
export type HeartbeatReply = Message<"bilibili.api.player.v1.HeartbeatReply"> & {
  /**
   * 时间戳
   *
   * @generated from field: int64 ts = 1;
   */
  ts: bigint;
};

/**
 * Describes the message bilibili.api.player.v1.HeartbeatReply.
 * Use `create(HeartbeatReplySchema)` to create a new message.
 */
export const HeartbeatReplySchema: GenMessage<HeartbeatReply> = /*@__PURE__*/
  messageDesc(file_bilibili_api_player_v1_player, 0);

/**
 * 客户端心跳上报-请求
 *
 * @generated from message bilibili.api.player.v1.HeartbeatReq
 */
export type HeartbeatReq = Message<"bilibili.api.player.v1.HeartbeatReq"> & {
  /**
   * @generated from field: int64 server_time = 1;
   */
  serverTime: bigint;

  /**
   * @generated from field: string session = 2;
   */
  session: string;

  /**
   * 用户 mid
   *
   * @generated from field: int64 mid = 3;
   */
  mid: bigint;

  /**
   * 稿件 avid
   *
   * @generated from field: int64 aid = 4;
   */
  aid: bigint;

  /**
   * 视频 cid
   *
   * @generated from field: int64 cid = 5;
   */
  cid: bigint;

  /**
   * @generated from field: string sid = 6;
   */
  sid: string;

  /**
   * @generated from field: int64 epid = 7;
   */
  epid: bigint;

  /**
   * @generated from field: string type = 8;
   */
  type: string;

  /**
   * @generated from field: int32 sub_type = 9;
   */
  subType: number;

  /**
   * @generated from field: int32 quality = 10;
   */
  quality: number;

  /**
   * @generated from field: int64 total_time = 11;
   */
  totalTime: bigint;

  /**
   * @generated from field: int64 paused_time = 12;
   */
  pausedTime: bigint;

  /**
   * @generated from field: int64 played_time = 13;
   */
  playedTime: bigint;

  /**
   * @generated from field: int64 video_duration = 14;
   */
  videoDuration: bigint;

  /**
   * @generated from field: string play_type = 15;
   */
  playType: string;

  /**
   * @generated from field: int32 network_type = 16;
   */
  networkType: number;

  /**
   * @generated from field: int64 last_play_progress_time = 17;
   */
  lastPlayProgressTime: bigint;

  /**
   * @generated from field: int64 max_play_progress_time = 18;
   */
  maxPlayProgressTime: bigint;

  /**
   * @generated from field: int32 from = 19;
   */
  from: number;

  /**
   * @generated from field: string from_spmid = 20;
   */
  fromSpmid: string;

  /**
   * @generated from field: string spmid = 21;
   */
  spmid: string;

  /**
   * @generated from field: string epid_status = 22;
   */
  epidStatus: string;

  /**
   * @generated from field: string play_status = 23;
   */
  playStatus: string;

  /**
   * @generated from field: string user_status = 24;
   */
  userStatus: string;

  /**
   * @generated from field: int64 actual_played_time = 25;
   */
  actualPlayedTime: bigint;

  /**
   * @generated from field: int32 auto_play = 26;
   */
  autoPlay: number;

  /**
   * @generated from field: int64 list_play_time = 27;
   */
  listPlayTime: bigint;

  /**
   * @generated from field: int64 detail_play_time = 28;
   */
  detailPlayTime: bigint;
};

/**
 * Describes the message bilibili.api.player.v1.HeartbeatReq.
 * Use `create(HeartbeatReqSchema)` to create a new message.
 */
export const HeartbeatReqSchema: GenMessage<HeartbeatReq> = /*@__PURE__*/
  messageDesc(file_bilibili_api_player_v1_player, 1);

/**
 * 心跳上报
 *
 * @generated from service bilibili.api.player.v1.Heartbeat
 */
export const Heartbeat: GenService<{
  /**
   * 客户端心跳上报
   *
   * @generated from rpc bilibili.api.player.v1.Heartbeat.Mobile
   */
  mobile: {
    methodKind: "unary";
    input: typeof HeartbeatReqSchema;
    output: typeof HeartbeatReplySchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_bilibili_api_player_v1_player, 0);

