// @generated by protoc-gen-es v2.14.1 with parameter "target=ts"
// @generated from file bilibili/app/card/v1/card.proto (package bilibili.app.card.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { DynamicHot, HotTopic, LargeCoverV1, LargeCoverV4, MiddleCoverV3, PopularTopEntrance, RcmdOneItem, SmallCoverV5, SmallCoverV5Ad, ThreeItemAllV2, ThreeItemV1 } from "./single_pb";
import { file_bilibili_app_card_v1_single } from "./single_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file bilibili/app/card/v1/card.proto.
 */
export const file_bilibili_app_card_v1_card: GenFile = /*@__PURE__*/
  fileDesc("Ch9iaWxpYmlsaS9hcHAvY2FyZC92MS9jYXJkLnByb3RvEhRiaWxpYmlsaS5hcHAuY2FyZC52MSLCBQoEQ2FyZBI8Cg5zbWFsbF9jb3Zlcl92NRgBIAEoCzIiLmJpbGliaWxpLmFwcC5jYXJkLnYxLlNtYWxsQ292ZXJWNUgAEjwKDmxhcmdlX2NvdmVyX3YxGAIgASgLMiIuYmlsaWJpbGkuYXBwLmNhcmQudjEuTGFyZ2VDb3ZlclYxSAASQQoRdGhyZWVfaXRlbV9hbGxfdjIYAyABKAsyJC5iaWxpYmlsaS5hcHAuY2FyZC52MS5UaHJlZUl0ZW1BbGxWMkgAEjoKDXRocmVlX2l0ZW1fdjEYBCABKAsyIS5iaWxpYmlsaS5hcHAuY2FyZC52MS5UaHJlZUl0ZW1WMUgAEjMKCWhvdF90b3BpYxgFIAEoCzIeLmJpbGliaWxpLmFwcC5jYXJkLnYxLkhvdFRvcGljSAASOwoPdGhyZWVfaXRlbV9oX3Y1GAYgASgLMiAuYmlsaWJpbGkuYXBwLmNhcmQudjEuRHluYW1pY0hvdEgAEj4KD21pZGRsZV9jb3Zlcl92MxgHIAEoCzIjLmJpbGliaWxpLmFwcC5jYXJkLnYxLk1pZGRsZUNvdmVyVjNIABI8Cg5sYXJnZV9jb3Zlcl92NBgIIAEoCzIiLmJpbGliaWxpLmFwcC5jYXJkLnYxLkxhcmdlQ292ZXJWNEgAEkgKFHBvcHVsYXJfdG9wX2VudHJhbmNlGAkgASgLMiguYmlsaWJpbGkuYXBwLmNhcmQudjEuUG9wdWxhclRvcEVudHJhbmNlSAASOgoNcmNtZF9vbmVfaXRlbRgKIAEoCzIhLmJpbGliaWxpLmFwcC5jYXJkLnYxLlJjbWRPbmVJdGVtSAASQQoRc21hbGxfY292ZXJfdjVfYWQYCyABKAsyJC5iaWxpYmlsaS5hcHAuY2FyZC52MS5TbWFsbENvdmVyVjVBZEgAQgYKBGl0ZW1iBnByb3RvMw", [file_bilibili_app_card_v1_single]);

/**
 * 卡片信息
 *
 * @generated from message bilibili.app.card.v1.Card
 */
export type Card = Message<"bilibili.app.card.v1.Card"> & {
  /**
   * @generated from oneof bilibili.app.card.v1.Card.item
   */
  item: {
    /**
     * 小封面条目
     *
     * @generated from field: bilibili.app.card.v1.SmallCoverV5 small_cover_v5 = 1;
     */
    value: SmallCoverV5;
    case: "smallCoverV5";
  } | {
    /**
     * @generated from field: bilibili.app.card.v1.LargeCoverV1 large_cover_v1 = 2;
     */
    value: LargeCoverV1;
    case: "largeCoverV1";
  } | {
    /**
     * @generated from field: bilibili.app.card.v1.ThreeItemAllV2 three_item_all_v2 = 3;
     */
    value: ThreeItemAllV2;
    case: "threeItemAllV2";
  } | {
    /**
     * @generated from field: bilibili.app.card.v1.ThreeItemV1 three_item_v1 = 4;
     */
    value: ThreeItemV1;
    case: "threeItemV1";
  } | {
    /**
     * @generated from field: bilibili.app.card.v1.HotTopic hot_topic = 5;
     */
    value: HotTopic;
    case: "hotTopic";
  } | {
    /**
     * @generated from field: bilibili.app.card.v1.DynamicHot three_item_h_v5 = 6;
     */
    value: DynamicHot;
    case: "threeItemHV5";
  } | {
    /**
     * @generated from field: bilibili.app.card.v1.MiddleCoverV3 middle_cover_v3 = 7;
     */
    value: MiddleCoverV3;
    case: "middleCoverV3";
  } | {
    /**
     * @generated from field: bilibili.app.card.v1.LargeCoverV4 large_cover_v4 = 8;
     */
    value: LargeCoverV4;
    case: "largeCoverV4";
  } | {
    /**
     * 热门列表顶部按钮
     *
     * @generated from field: bilibili.app.card.v1.PopularTopEntrance popular_top_entrance = 9;
     */
    value: PopularTopEntrance;
    case: "popularTopEntrance";
  } | {
    /**
     * @generated from field: bilibili.app.card.v1.RcmdOneItem rcmd_one_item = 10;
     */
    value: RcmdOneItem;
    case: "rcmdOneItem";
  } | {
    /**
     * @generated from field: bilibili.app.card.v1.SmallCoverV5Ad small_cover_v5_ad = 11;
     */
    value: SmallCoverV5Ad;
    case: "smallCoverV5Ad";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message bilibili.app.card.v1.Card.
 * Use `create(CardSchema)` to create a new message.
 */
export const CardSchema: GenMessage<Card> = /*@__PURE__*/
  messageDesc(file_bilibili_app_card_v1_card, 0);

