// @generated by protoc-gen-es v2.14.1 with parameter "target=ts"
// @generated from file bilibili/app/playerunite/pugvanymodel.proto/pugvanymodel.proto (package bilibili.app.playerunite.pugvanymodel, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file bilibili/app/playerunite/pugvanymodel.proto/pugvanymodel.proto.
 */
export const file_bilibili_app_playerunite_pugvanymodel_proto_pugvanymodel: GenFile = /*@__PURE__*/
  fileDesc("Cj5iaWxpYmlsaS9hcHAvcGxheWVydW5pdGUvcHVndmFueW1vZGVsLnByb3RvL3B1Z3Zhbnltb2RlbC5wcm90bxIlYmlsaWJpbGkuYXBwLnBsYXllcnVuaXRlLnB1Z3Zhbnltb2RlbCI7CgpQbGF5ZXJNYXNrEg0KBXRpdGxlGAEgASgJEg4KBnByZWZpeBgCIAEoCRIOCgZzdWZmaXgYAyABKAkijQIKDFBVR1ZBbnlNb2RlbBIRCglzZWFzb25faWQYASABKAMSEgoKZXBpc29kZV9pZBgCIAEoAxJECgZzdGF0dXMYAyABKA4yNC5iaWxpYmlsaS5hcHAucGxheWVydW5pdGUucHVndmFueW1vZGVsLkVwaXNvZGVTdGF0dXMSSAoMcmlza19jb250cm9sGAQgASgLMjIuYmlsaWJpbGkuYXBwLnBsYXllcnVuaXRlLnB1Z3Zhbnltb2RlbC5SaXNrQ29udHJvbBJGCgtwbGF5ZXJfbWFzaxgFIAEoCzIxLmJpbGliaWxpLmFwcC5wbGF5ZXJ1bml0ZS5wdWd2YW55bW9kZWwuUGxheWVyTWFzayKDAQoLUmlza0NvbnRyb2wSFQoNbmVlZF9zZW5kX3NtcxgBIAEoCBINCgV0aXRsZRgCIAEoCRIUCgxyaXNrX21lc3NhZ2UYAyABKAkSEwoLYWN0aW9uX2Rlc2MYBCABKAkSFAoMc2VuZF9zbXNfdXJsGAUgASgJEg0KBWJ1dmlkGAYgASgJKp0BCg1FcGlzb2RlU3RhdHVzEh4KGkVQSVNPREVfU1RBVFVTX1VOU1BFQ0lGSUVEEAASIgoeRVBJU09ERV9TVEFUVVNfVFJZX1dBVENIX1dIT0xFEAESIAocRVBJU09ERV9TVEFUVVNfTk9UX1RSWV9XQVRDSBACEiYKIkVQSVNPREVfU1RBVFVTX1RSWV9XQVRDSF81X01JTlVURVMQA2IGcHJvdG8z");

/**
 *
 *
 * @generated from message bilibili.app.playerunite.pugvanymodel.PlayerMask
 */
export type PlayerMask = Message<"bilibili.app.playerunite.pugvanymodel.PlayerMask"> & {
  /**
   *
   *
   * @generated from field: string title = 1;
   */
  title: string;

  /**
   *
   *
   * @generated from field: string prefix = 2;
   */
  prefix: string;

  /**
   *
   *
   * @generated from field: string suffix = 3;
   */
  suffix: string;
};

/**
 * Describes the message bilibili.app.playerunite.pugvanymodel.PlayerMask.
 * Use `create(PlayerMaskSchema)` to create a new message.
 */
export const PlayerMaskSchema: GenMessage<PlayerMask> = /*@__PURE__*/
  messageDesc(file_bilibili_app_playerunite_pugvanymodel_proto_pugvanymodel, 0);

/**
 *
 *
 * @generated from message bilibili.app.playerunite.pugvanymodel.PUGVAnyModel
 */
export type PUGVAnyModel = Message<"bilibili.app.playerunite.pugvanymodel.PUGVAnyModel"> & {
  /**
   *
   *
   * @generated from field: int64 season_id = 1;
   */
  seasonId: bigint;

  /**
   *
   *
   * @generated from field: int64 episode_id = 2;
   */
  episodeId: bigint;

  /**
   *
   *
   * @generated from field: bilibili.app.playerunite.pugvanymodel.EpisodeStatus status = 3;
   */
  status: EpisodeStatus;

  /**
   *
   *
   * @generated from field: bilibili.app.playerunite.pugvanymodel.RiskControl risk_control = 4;
   */
  riskControl?: RiskControl | undefined;

  /**
   *
   *
   * @generated from field: bilibili.app.playerunite.pugvanymodel.PlayerMask player_mask = 5;
   */
  playerMask?: PlayerMask | undefined;
};

/**
 * Describes the message bilibili.app.playerunite.pugvanymodel.PUGVAnyModel.
 * Use `create(PUGVAnyModelSchema)` to create a new message.
 */
export const PUGVAnyModelSchema: GenMessage<PUGVAnyModel> = /*@__PURE__*/
  messageDesc(file_bilibili_app_playerunite_pugvanymodel_proto_pugvanymodel, 1);

/**
 *
 *
 * @generated from message bilibili.app.playerunite.pugvanymodel.RiskControl
 */
export type RiskControl = Message<"bilibili.app.playerunite.pugvanymodel.RiskControl"> & {
  /**
   *
   *
   * @generated from field: bool need_send_sms = 1;
   */
  needSendSms: boolean;

  /**
   *
   *
   * @generated from field: string title = 2;
   */
  title: string;

  /**
   *
   *
   * @generated from field: string risk_message = 3;
   */
  riskMessage: string;

  /**
   *
   *
   * @generated from field: string action_desc = 4;
   */
  actionDesc: string;

  /**
   *
   *
   * @generated from field: string send_sms_url = 5;
   */
  sendSmsUrl: string;

  /**
   *
   *
   * @generated from field: string buvid = 6;
   */
  buvid: string;
};

/**
 * Describes the message bilibili.app.playerunite.pugvanymodel.RiskControl.
 * Use `create(RiskControlSchema)` to create a new message.
 */
export const RiskControlSchema: GenMessage<RiskControl> = /*@__PURE__*/
  messageDesc(file_bilibili_app_playerunite_pugvanymodel_proto_pugvanymodel, 2);

/**
 *
 *
 * @generated from enum bilibili.app.playerunite.pugvanymodel.EpisodeStatus
 */
export enum EpisodeStatus {
  /**
   * @generated from enum value: EPISODE_STATUS_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: EPISODE_STATUS_TRY_WATCH_WHOLE = 1;
   */
  TRY_WATCH_WHOLE = 1,

  /**
   * @generated from enum value: EPISODE_STATUS_NOT_TRY_WATCH = 2;
   */
  NOT_TRY_WATCH = 2,

  /**
   * @generated from enum value: EPISODE_STATUS_TRY_WATCH_5_MINUTES = 3;
   */
  TRY_WATCH_5_MINUTES = 3,
}

/**
 * Describes the enum bilibili.app.playerunite.pugvanymodel.EpisodeStatus.
 */
export const EpisodeStatusSchema: GenEnum<EpisodeStatus> = /*@__PURE__*/
  enumDesc(file_bilibili_app_playerunite_pugvanymodel_proto_pugvanymodel, 0);

