// @generated by protoc-gen-es v2.14.1 with parameter "target=ts"
// @generated from file bilibili/app/playerunite/ugcanymodel/ugcanymodel.proto (package bilibili.app.playerunite.ugcanymodel, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file bilibili/app/playerunite/ugcanymodel/ugcanymodel.proto.
 */
export const file_bilibili_app_playerunite_ugcanymodel_ugcanymodel: GenFile = /*@__PURE__*/
  fileDesc("CjZiaWxpYmlsaS9hcHAvcGxheWVydW5pdGUvdWdjYW55bW9kZWwvdWdjYW55bW9kZWwucHJvdG8SJGJpbGliaWxpLmFwcC5wbGF5ZXJ1bml0ZS51Z2Nhbnltb2RlbCJUCgtCdXR0b25TdHlsZRIMCgR0ZXh0GAEgASgJEhIKCnRleHRfY29sb3IYAiABKAkSEAoIYmdfY29sb3IYAyABKAkSEQoJanVtcF9saW5rGAQgASgJIrcBCglQbGF5TGltaXQSQQoEY29kZRgBIAEoDjIzLmJpbGliaWxpLmFwcC5wbGF5ZXJ1bml0ZS51Z2Nhbnltb2RlbC5QbGF5TGltaXRDb2RlEg8KB21lc3NhZ2UYAiABKAkSEwoLc3ViX21lc3NhZ2UYAyABKAkSQQoGYnV0dG9uGAQgASgLMjEuYmlsaWJpbGkuYXBwLnBsYXllcnVuaXRlLnVnY2FueW1vZGVsLkJ1dHRvblN0eWxlIlIKC1VHQ0FueU1vZGVsEkMKCnBsYXlfbGltaXQYASABKAsyLy5iaWxpYmlsaS5hcHAucGxheWVydW5pdGUudWdjYW55bW9kZWwuUGxheUxpbWl0KogBCg1QbGF5TGltaXRDb2RlEg8KC1BMQ19VTktOT1dOEAASEAoMUExDX05PVFBBWUVEEAESGwoXUExDX0NoYXJnaW5nUGx1c05vdFBhc3MQAhIbChdQTENfQ2hhcmdpbmdQbHVzVXBncmFkZRADEhoKFlBMQ19DaGFyZ2luZ1BsdXNSZWplY3QQBGIGcHJvdG8z");

/**
 * 
 *
 * @generated from message bilibili.app.playerunite.ugcanymodel.ButtonStyle
 */
export type ButtonStyle = Message<"bilibili.app.playerunite.ugcanymodel.ButtonStyle"> & {
  /**
   * @generated from field: string text = 1;
   */
  text: string;

  /**
   * @generated from field: string text_color = 2;
   */
  textColor: string;

  /**
   * @generated from field: string bg_color = 3;
   */
  bgColor: string;

  /**
   * @generated from field: string jump_link = 4;
   */
  jumpLink: string;
};

/**
 * Describes the message bilibili.app.playerunite.ugcanymodel.ButtonStyle.
 * Use `create(ButtonStyleSchema)` to create a new message.
 */
export const ButtonStyleSchema: GenMessage<ButtonStyle> = /*@__PURE__*/
  messageDesc(file_bilibili_app_playerunite_ugcanymodel_ugcanymodel, 0);

/**
 * 
 *
 * @generated from message bilibili.app.playerunite.ugcanymodel.PlayLimit
 */
export type PlayLimit = Message<"bilibili.app.playerunite.ugcanymodel.PlayLimit"> & {
  /**
   * @generated from field: bilibili.app.playerunite.ugcanymodel.PlayLimitCode code = 1;
   */
  code: PlayLimitCode;

  /**
   * @generated from field: string message = 2;
   */
  message: string;

  /**
   * @generated from field: string sub_message = 3;
   */
  subMessage: string;

  /**
   * @generated from field: bilibili.app.playerunite.ugcanymodel.ButtonStyle button = 4;
   */
  button?: ButtonStyle | undefined;
};

/**
 * Describes the message bilibili.app.playerunite.ugcanymodel.PlayLimit.
 * Use `create(PlayLimitSchema)` to create a new message.
 */
export const PlayLimitSchema: GenMessage<PlayLimit> = /*@__PURE__*/
  messageDesc(file_bilibili_app_playerunite_ugcanymodel_ugcanymodel, 1);

/**
 * 
 *
 * @generated from message bilibili.app.playerunite.ugcanymodel.UGCAnyModel
 */
export type UGCAnyModel = Message<"bilibili.app.playerunite.ugcanymodel.UGCAnyModel"> & {
  /**
   * @generated from field: bilibili.app.playerunite.ugcanymodel.PlayLimit play_limit = 1;
   */
  playLimit?: PlayLimit | undefined;
};

/**
 * Describes the message bilibili.app.playerunite.ugcanymodel.UGCAnyModel.
 * Use `create(UGCAnyModelSchema)` to create a new message.
 */
export const UGCAnyModelSchema: GenMessage<UGCAnyModel> = /*@__PURE__*/
  messageDesc(file_bilibili_app_playerunite_ugcanymodel_ugcanymodel, 2);

/**
 * 播放限制
 *
 * @generated from enum bilibili.app.playerunite.ugcanymodel.PlayLimitCode
 */
export enum PlayLimitCode {
  /**
   * 
   *
   * @generated from enum value: PLC_UNKNOWN = 0;
   */
  PLC_UNKNOWN = 0,

  /**
   * 未付费
   *
   * @generated from enum value: PLC_NOTPAYED = 1;
   */
  PLC_NOTPAYED = 1,

  /**
   * 
   *
   * @generated from enum value: PLC_ChargingPlusNotPass = 2;
   */
  PLC_ChargingPlusNotPass = 2,

  /**
   * 
   *
   * @generated from enum value: PLC_ChargingPlusUpgrade = 3;
   */
  PLC_ChargingPlusUpgrade = 3,

  /**
   * 
   *
   * @generated from enum value: PLC_ChargingPlusReject = 4;
   */
  PLC_ChargingPlusReject = 4,
}

/**
 * Describes the enum bilibili.app.playerunite.ugcanymodel.PlayLimitCode.
 */
export const PlayLimitCodeSchema: GenEnum<PlayLimitCode> = /*@__PURE__*/
  enumDesc(file_bilibili_app_playerunite_ugcanymodel_ugcanymodel, 0);

