// @generated by protoc-gen-es v2.14.1 with parameter "target=ts"
// @generated from file bilibili/metadata/device/device.proto (package bilibili.metadata.device, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file bilibili/metadata/device/device.proto.
 */
export const file_bilibili_metadata_device_device: GenFile = /*@__PURE__*/
  fileDesc("CiViaWxpYmlsaS9tZXRhZGF0YS9kZXZpY2UvZGV2aWNlLnByb3RvEhhiaWxpYmlsaS5tZXRhZGF0YS5kZXZpY2Ui/AEKBkRldmljZRIOCgZhcHBfaWQYASABKAUSDQoFYnVpbGQYAiABKAUSDQoFYnV2aWQYAyABKAkSEAoIbW9iaV9hcHAYBCABKAkSEAoIcGxhdGZvcm0YBSABKAkSDgoGZGV2aWNlGAYgASgJEg8KB2NoYW5uZWwYByABKAkSDQoFYnJhbmQYCCABKAkSDQoFbW9kZWwYCSABKAkSDQoFb3N2ZXIYCiABKAkSEAoIZnBfbG9jYWwYCyABKAkSEQoJZnBfcmVtb3RlGAwgASgJEhQKDHZlcnNpb25fbmFtZRgNIAEoCRIKCgJmcBgOIAEoCRILCgNmdHMYDyABKANiBnByb3RvMw");

/**
 * 设备信息
 * gRPC头部:x-bili-device-bin
 *
 * @generated from message bilibili.metadata.device.Device
 */
export type Device = Message<"bilibili.metadata.device.Device"> & {
  /**
   * 产品id
   * 粉 白 蓝 直播姬 HD 海外 OTT 漫画 TV野版 小视频 网易漫画 网易漫画 网易漫画HD 国际版 东南亚版
   * 1  2  3    4    5   6    7   8     9     10      11       12       13       14       30
   *
   * @generated from field: int32 app_id = 1;
   */
  appId: number;

  /**
   * 构建id
   *
   * @generated from field: int32 build = 2;
   */
  build: number;

  /**
   * 设备buvid
   *
   * @generated from field: string buvid = 3;
   */
  buvid: string;

  /**
   * 包类型
   *
   * @generated from field: string mobi_app = 4;
   */
  mobiApp: string;

  /**
   * 平台类型
   * ios android
   *
   * @generated from field: string platform = 5;
   */
  platform: string;

  /**
   * 设备类型
   *
   * @generated from field: string device = 6;
   */
  device: string;

  /**
   * 渠道
   *
   * @generated from field: string channel = 7;
   */
  channel: string;

  /**
   * 手机品牌
   *
   * @generated from field: string brand = 8;
   */
  brand: string;

  /**
   * 手机型号
   *
   * @generated from field: string model = 9;
   */
  model: string;

  /**
   * 系统版本
   *
   * @generated from field: string osver = 10;
   */
  osver: string;

  /**
   * 本地设备指纹
   *
   * @generated from field: string fp_local = 11;
   */
  fpLocal: string;

  /**
   * 远程设备指纹
   *
   * @generated from field: string fp_remote = 12;
   */
  fpRemote: string;

  /**
   * APP版本号
   *
   * @generated from field: string version_name = 13;
   */
  versionName: string;

  /**
   * 设备指纹, 不区分本地或远程设备指纹，作为推送目标的索引
   *
   * @generated from field: string fp = 14;
   */
  fp: string;

  /**
   * 首次启动时的毫秒时间戳
   *
   * @generated from field: int64 fts = 15;
   */
  fts: bigint;
};

/**
 * Describes the message bilibili.metadata.device.Device.
 * Use `create(DeviceSchema)` to create a new message.
 */
export const DeviceSchema: GenMessage<Device> = /*@__PURE__*/
  messageDesc(file_bilibili_metadata_device_device, 0);

