// @generated by protoc-gen-es v2.14.1 with parameter "target=ts"
// @generated from file bilibili/metadata/restriction/restriction.proto (package bilibili.metadata.restriction, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file bilibili/metadata/restriction/restriction.proto.
 */
export const file_bilibili_metadata_restriction_restriction: GenFile = /*@__PURE__*/
  fileDesc("Ci9iaWxpYmlsaS9tZXRhZGF0YS9yZXN0cmljdGlvbi9yZXN0cmljdGlvbi5wcm90bxIdYmlsaWJpbGkubWV0YWRhdGEucmVzdHJpY3Rpb24irAEKC1Jlc3RyaWN0aW9uEhYKDnRlZW5hZ2Vyc19tb2RlGAEgASgIEhQKDGxlc3NvbnNfbW9kZRgCIAEoCBI1CgRtb2RlGAMgASgOMicuYmlsaWJpbGkubWV0YWRhdGEucmVzdHJpY3Rpb24uTW9kZVR5cGUSDgoGcmV2aWV3GAQgASgIEhQKDGRpc2FibGVfcmNtZBgFIAEoCBISCgpiYXNpY19tb2RlGAYgASgIKj0KCE1vZGVUeXBlEgoKBk5PUk1BTBAAEg0KCVRFRU5BR0VSUxABEgsKB0xFU1NPTlMQAhIJCgVCQVNJQxADYgZwcm90bzM");

/**
 * 限制条件
 *
 * @generated from message bilibili.metadata.restriction.Restriction
 */
export type Restriction = Message<"bilibili.metadata.restriction.Restriction"> & {
  /**
   * 青少年模式开关状态
   *
   * @generated from field: bool teenagers_mode = 1;
   */
  teenagersMode: boolean;

  /**
   * 课堂模式开关状态
   *
   * @generated from field: bool lessons_mode = 2;
   */
  lessonsMode: boolean;

  /**
   * 模式类型(旧版)
   *
   * @generated from field: bilibili.metadata.restriction.ModeType mode = 3;
   */
  mode: ModeType;

  /**
   * app 审核review状态
   *
   * @generated from field: bool review = 4;
   */
  review: boolean;

  /**
   * 客户端是否选择关闭个性化推荐
   *
   * @generated from field: bool disable_rcmd = 5;
   */
  disableRcmd: boolean;

  /**
   *
   *
   * @generated from field: bool basic_mode = 6;
   */
  basicMode: boolean;
};

/**
 * Describes the message bilibili.metadata.restriction.Restriction.
 * Use `create(RestrictionSchema)` to create a new message.
 */
export const RestrictionSchema: GenMessage<Restriction> = /*@__PURE__*/
  messageDesc(file_bilibili_metadata_restriction_restriction, 0);

/**
 * 模式类型
 *
 * @generated from enum bilibili.metadata.restriction.ModeType
 */
export enum ModeType {
  /**
   * 正常模式
   *
   * @generated from enum value: NORMAL = 0;
   */
  NORMAL = 0,

  /**
   * 青少年模式
   *
   * @generated from enum value: TEENAGERS = 1;
   */
  TEENAGERS = 1,

  /**
   * 课堂模式
   *
   * @generated from enum value: LESSONS = 2;
   */
  LESSONS = 2,

  /**
   *
   *
   * @generated from enum value: BASIC = 3;
   */
  BASIC = 3,
}

/**
 * Describes the enum bilibili.metadata.restriction.ModeType.
 */
export const ModeTypeSchema: GenEnum<ModeType> = /*@__PURE__*/
  enumDesc(file_bilibili_metadata_restriction_restriction, 0);

