// @generated by protoc-gen-es v2.14.1 with parameter "target=ts"
// @generated from file bilibili/pagination/pagination.proto (package bilibili.pagination, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file bilibili/pagination/pagination.proto.
 */
export const file_bilibili_pagination_pagination: GenFile = /*@__PURE__*/
  fileDesc("CiRiaWxpYmlsaS9wYWdpbmF0aW9uL3BhZ2luYXRpb24ucHJvdG8SE2JpbGliaWxpLnBhZ2luYXRpb24iRwoORmVlZFBhZ2luYXRpb24SEQoJcGFnZV9zaXplGAEgASgFEg4KBm9mZnNldBgCIAEoCRISCgppc19yZWZyZXNoGAMgASgIIlkKE0ZlZWRQYWdpbmF0aW9uUmVwbHkSEwoLbmV4dF9vZmZzZXQYASABKAkSEwoLcHJldl9vZmZzZXQYAiABKAkSGAoQbGFzdF9yZWFkX29mZnNldBgDIAEoCSItCgpQYWdpbmF0aW9uEhEKCXBhZ2Vfc2l6ZRgBIAEoBRIMCgRuZXh0GAIgASgJIi0KD1BhZ2luYXRpb25SZXBseRIMCgRuZXh0GAEgASgJEgwKBHByZXYYAiABKAliBnByb3RvMw");

/**
 * 分页信息
 *
 * @generated from message bilibili.pagination.FeedPagination
 */
export type FeedPagination = Message<"bilibili.pagination.FeedPagination"> & {
  /**
   * @generated from field: int32 page_size = 1;
   */
  pageSize: number;

  /**
   * @generated from field: string offset = 2;
   */
  offset: string;

  /**
   * @generated from field: bool is_refresh = 3;
   */
  isRefresh: boolean;
};

/**
 * Describes the message bilibili.pagination.FeedPagination.
 * Use `create(FeedPaginationSchema)` to create a new message.
 */
export const FeedPaginationSchema: GenMessage<FeedPagination> = /*@__PURE__*/
  messageDesc(file_bilibili_pagination_pagination, 0);

/**
 * 分页信息
 *
 * @generated from message bilibili.pagination.FeedPaginationReply
 */
export type FeedPaginationReply = Message<"bilibili.pagination.FeedPaginationReply"> & {
  /**
   * @generated from field: string next_offset = 1;
   */
  nextOffset: string;

  /**
   * @generated from field: string prev_offset = 2;
   */
  prevOffset: string;

  /**
   * @generated from field: string last_read_offset = 3;
   */
  lastReadOffset: string;
};

/**
 * Describes the message bilibili.pagination.FeedPaginationReply.
 * Use `create(FeedPaginationReplySchema)` to create a new message.
 */
export const FeedPaginationReplySchema: GenMessage<FeedPaginationReply> = /*@__PURE__*/
  messageDesc(file_bilibili_pagination_pagination, 1);

/**
 * 分页信息
 *
 * @generated from message bilibili.pagination.Pagination
 */
export type Pagination = Message<"bilibili.pagination.Pagination"> & {
  /**
   * @generated from field: int32 page_size = 1;
   */
  pageSize: number;

  /**
   * @generated from field: string next = 2;
   */
  next: string;
};

/**
 * Describes the message bilibili.pagination.Pagination.
 * Use `create(PaginationSchema)` to create a new message.
 */
export const PaginationSchema: GenMessage<Pagination> = /*@__PURE__*/
  messageDesc(file_bilibili_pagination_pagination, 2);

/**
 * 分页信息
 *
 * @generated from message bilibili.pagination.PaginationReply
 */
export type PaginationReply = Message<"bilibili.pagination.PaginationReply"> & {
  /**
   * @generated from field: string next = 1;
   */
  next: string;

  /**
   * @generated from field: string prev = 2;
   */
  prev: string;
};

/**
 * Describes the message bilibili.pagination.PaginationReply.
 * Use `create(PaginationReplySchema)` to create a new message.
 */
export const PaginationReplySchema: GenMessage<PaginationReply> = /*@__PURE__*/
  messageDesc(file_bilibili_pagination_pagination, 3);

