// @generated by protoc-gen-es v2.14.1 with parameter "target=ts"
// @generated from file bilibili/app/distribution/setting/download.proto (package bilibili.app.distribution.setting.download, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { BoolValue } from "../v1/distribution_pb";
import { file_bilibili_app_distribution_v1_distribution } from "../v1/distribution_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file bilibili/app/distribution/setting/download.proto.
 */
export const file_bilibili_app_distribution_setting_download: GenFile = /*@__PURE__*/
  fileDesc("CjBiaWxpYmlsaS9hcHAvZGlzdHJpYnV0aW9uL3NldHRpbmcvZG93bmxvYWQucHJvdG8SKmJpbGliaWxpLmFwcC5kaXN0cmlidXRpb24uc2V0dGluZy5kb3dubG9hZCJlChZEb3dubG9hZFNldHRpbmdzQ29uZmlnEksKGmVuYWJsZV9kb3dubG9hZF9hdXRvX3N0YXJ0GAEgASgLMicuYmlsaWJpbGkuYXBwLmRpc3RyaWJ1dGlvbi52MS5Cb29sVmFsdWViBnByb3RvMw", [file_bilibili_app_distribution_v1_distribution]);

/**
 * 
 *
 * @generated from message bilibili.app.distribution.setting.download.DownloadSettingsConfig
 */
export type DownloadSettingsConfig = Message<"bilibili.app.distribution.setting.download.DownloadSettingsConfig"> & {
  /**
   * 
   *
   * @generated from field: bilibili.app.distribution.v1.BoolValue enable_download_auto_start = 1;
   */
  enableDownloadAutoStart?: BoolValue | undefined;
};

/**
 * Describes the message bilibili.app.distribution.setting.download.DownloadSettingsConfig.
 * Use `create(DownloadSettingsConfigSchema)` to create a new message.
 */
export const DownloadSettingsConfigSchema: GenMessage<DownloadSettingsConfig> = /*@__PURE__*/
  messageDesc(file_bilibili_app_distribution_setting_download, 0);

