// @generated by protoc-gen-es v2.14.1 with parameter "target=ts"
// @generated from file bilibili/app/distribution/setting/dynamic.proto (package bilibili.app.distribution.setting.dynamic, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Int64Value } from "../v1/distribution_pb";
import { file_bilibili_app_distribution_v1_distribution } from "../v1/distribution_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file bilibili/app/distribution/setting/dynamic.proto.
 */
export const file_bilibili_app_distribution_setting_dynamic: GenFile = /*@__PURE__*/
  fileDesc("Ci9iaWxpYmlsaS9hcHAvZGlzdHJpYnV0aW9uL3NldHRpbmcvZHluYW1pYy5wcm90bxIpYmlsaWJpbGkuYXBwLmRpc3RyaWJ1dGlvbi5zZXR0aW5nLmR5bmFtaWMiSgoPRHluYW1pY0F1dG9QbGF5EjcKBXZhbHVlGAEgASgLMiguYmlsaWJpbGkuYXBwLmRpc3RyaWJ1dGlvbi52MS5JbnQ2NFZhbHVlImQKE0R5bmFtaWNEZXZpY2VDb25maWcSTQoJYXV0b19wbGF5GAEgASgLMjouYmlsaWJpbGkuYXBwLmRpc3RyaWJ1dGlvbi5zZXR0aW5nLmR5bmFtaWMuRHluYW1pY0F1dG9QbGF5YgZwcm90bzM", [file_bilibili_app_distribution_v1_distribution]);

/**
 * 
 *
 * @generated from message bilibili.app.distribution.setting.dynamic.DynamicAutoPlay
 */
export type DynamicAutoPlay = Message<"bilibili.app.distribution.setting.dynamic.DynamicAutoPlay"> & {
  /**
   * 
   *
   * @generated from field: bilibili.app.distribution.v1.Int64Value value = 1;
   */
  value?: Int64Value | undefined;
};

/**
 * Describes the message bilibili.app.distribution.setting.dynamic.DynamicAutoPlay.
 * Use `create(DynamicAutoPlaySchema)` to create a new message.
 */
export const DynamicAutoPlaySchema: GenMessage<DynamicAutoPlay> = /*@__PURE__*/
  messageDesc(file_bilibili_app_distribution_setting_dynamic, 0);

/**
 * 
 *
 * @generated from message bilibili.app.distribution.setting.dynamic.DynamicDeviceConfig
 */
export type DynamicDeviceConfig = Message<"bilibili.app.distribution.setting.dynamic.DynamicDeviceConfig"> & {
  /**
   * 
   *
   * @generated from field: bilibili.app.distribution.setting.dynamic.DynamicAutoPlay auto_play = 1;
   */
  autoPlay?: DynamicAutoPlay | undefined;
};

/**
 * Describes the message bilibili.app.distribution.setting.dynamic.DynamicDeviceConfig.
 * Use `create(DynamicDeviceConfigSchema)` to create a new message.
 */
export const DynamicDeviceConfigSchema: GenMessage<DynamicDeviceConfig> = /*@__PURE__*/
  messageDesc(file_bilibili_app_distribution_setting_dynamic, 1);

