// @generated by protoc-gen-es v2.14.1 with parameter "target=ts"
// @generated from file bilibili/app/distribution/setting/internaldevice.proto (package bilibili.app.distribution.setting.internaldevice, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Int64Value } from "../v1/distribution_pb";
import { file_bilibili_app_distribution_v1_distribution } from "../v1/distribution_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file bilibili/app/distribution/setting/internaldevice.proto.
 */
export const file_bilibili_app_distribution_setting_internaldevice: GenFile = /*@__PURE__*/
  fileDesc("CjZiaWxpYmlsaS9hcHAvZGlzdHJpYnV0aW9uL3NldHRpbmcvaW50ZXJuYWxkZXZpY2UucHJvdG8SMGJpbGliaWxpLmFwcC5kaXN0cmlidXRpb24uc2V0dGluZy5pbnRlcm5hbGRldmljZSJNChRJbnRlcm5hbERldmljZUNvbmZpZxI1CgNmdHMYASABKAsyKC5iaWxpYmlsaS5hcHAuZGlzdHJpYnV0aW9uLnYxLkludDY0VmFsdWViBnByb3RvMw", [file_bilibili_app_distribution_v1_distribution]);

/**
 * 
 *
 * @generated from message bilibili.app.distribution.setting.internaldevice.InternalDeviceConfig
 */
export type InternalDeviceConfig = Message<"bilibili.app.distribution.setting.internaldevice.InternalDeviceConfig"> & {
  /**
   * 首次启动时间
   *
   * @generated from field: bilibili.app.distribution.v1.Int64Value fts = 1;
   */
  fts?: Int64Value | undefined;
};

/**
 * Describes the message bilibili.app.distribution.setting.internaldevice.InternalDeviceConfig.
 * Use `create(InternalDeviceConfigSchema)` to create a new message.
 */
export const InternalDeviceConfigSchema: GenMessage<InternalDeviceConfig> = /*@__PURE__*/
  messageDesc(file_bilibili_app_distribution_setting_internaldevice, 0);

