// @generated by protoc-gen-es v2.14.1 with parameter "target=ts"
// @generated from file bilibili/app/distribution/setting/night.proto (package bilibili.app.distribution.setting.night, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { BoolValue } from "../v1/distribution_pb";
import { file_bilibili_app_distribution_v1_distribution } from "../v1/distribution_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file bilibili/app/distribution/setting/night.proto.
 */
export const file_bilibili_app_distribution_setting_night: GenFile = /*@__PURE__*/
  fileDesc("Ci1iaWxpYmlsaS9hcHAvZGlzdHJpYnV0aW9uL3NldHRpbmcvbmlnaHQucHJvdG8SJ2JpbGliaWxpLmFwcC5kaXN0cmlidXRpb24uc2V0dGluZy5uaWdodCJeChNOaWdodFNldHRpbmdzQ29uZmlnEkcKFmlzX25pZ2h0X2ZvbGxvd19zeXN0ZW0YASABKAsyJy5iaWxpYmlsaS5hcHAuZGlzdHJpYnV0aW9uLnYxLkJvb2xWYWx1ZWIGcHJvdG8z", [file_bilibili_app_distribution_v1_distribution]);

/**
 * 
 *
 * @generated from message bilibili.app.distribution.setting.night.NightSettingsConfig
 */
export type NightSettingsConfig = Message<"bilibili.app.distribution.setting.night.NightSettingsConfig"> & {
  /**
   * 
   *
   * @generated from field: bilibili.app.distribution.v1.BoolValue is_night_follow_system = 1;
   */
  isNightFollowSystem?: BoolValue | undefined;
};

/**
 * Describes the message bilibili.app.distribution.setting.night.NightSettingsConfig.
 * Use `create(NightSettingsConfigSchema)` to create a new message.
 */
export const NightSettingsConfigSchema: GenMessage<NightSettingsConfig> = /*@__PURE__*/
  messageDesc(file_bilibili_app_distribution_setting_night, 0);

