// @generated by protoc-gen-es v2.14.1 with parameter "target=ts"
// @generated from file bilibili/app/distribution/setting/other.proto (package bilibili.app.distribution.setting.other, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { BoolValue, Int64Value } from "../v1/distribution_pb";
import { file_bilibili_app_distribution_v1_distribution } from "../v1/distribution_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file bilibili/app/distribution/setting/other.proto.
 */
export const file_bilibili_app_distribution_setting_other: GenFile = /*@__PURE__*/
  fileDesc("Ci1iaWxpYmlsaS9hcHAvZGlzdHJpYnV0aW9uL3NldHRpbmcvb3RoZXIucHJvdG8SJ2JpbGliaWxpLmFwcC5kaXN0cmlidXRpb24uc2V0dGluZy5vdGhlciLbBAoTT3RoZXJTZXR0aW5nc0NvbmZpZxJACg53YXRlcm1hcmtfdHlwZRgBIAEoCzIoLmJpbGliaWxpLmFwcC5kaXN0cmlidXRpb24udjEuSW50NjRWYWx1ZRJIChZ3ZWJfaW1hZ2VfcXVhbGl0eV90eXBlGAIgASgLMiguYmlsaWJpbGkuYXBwLmRpc3RyaWJ1dGlvbi52MS5JbnQ2NFZhbHVlEkcKFmVuYWJsZV9yZWFkX3Bhc3RlYm9hcmQYAyABKAsyJy5iaWxpYmlsaS5hcHAuZGlzdHJpYnV0aW9uLnYxLkJvb2xWYWx1ZRJACg9wYXN0ZV9hdXRvX2p1bXAYBCABKAsyJy5iaWxpYmlsaS5hcHAuZGlzdHJpYnV0aW9uLnYxLkJvb2xWYWx1ZRJLChptaW5pX3NjcmVlbl9wbGF5X3doZW5fYmFjaxgFIAEoCzInLmJpbGliaWxpLmFwcC5kaXN0cmlidXRpb24udjEuQm9vbFZhbHVlEkYKFWVuYWJsZV9yZXN1bWVfcGxheWluZxgGIAEoCzInLmJpbGliaWxpLmFwcC5kaXN0cmlidXRpb24udjEuQm9vbFZhbHVlEkgKF2VuYWJsZV93aWZpX2F1dG9fdXBkYXRlGAcgASgLMicuYmlsaWJpbGkuYXBwLmRpc3RyaWJ1dGlvbi52MS5Cb29sVmFsdWUSTgodZW5hYmxlX2d1aWRlX3NjcmVlbnNob3Rfc2hhcmUYCCABKAsyJy5iaWxpYmlsaS5hcHAuZGlzdHJpYnV0aW9uLnYxLkJvb2xWYWx1ZWIGcHJvdG8z", [file_bilibili_app_distribution_v1_distribution]);

/**
 * 
 *
 * @generated from message bilibili.app.distribution.setting.other.OtherSettingsConfig
 */
export type OtherSettingsConfig = Message<"bilibili.app.distribution.setting.other.OtherSettingsConfig"> & {
  /**
   * 
   *
   * @generated from field: bilibili.app.distribution.v1.Int64Value watermark_type = 1;
   */
  watermarkType?: Int64Value | undefined;

  /**
   * 
   *
   * @generated from field: bilibili.app.distribution.v1.Int64Value web_image_quality_type = 2;
   */
  webImageQualityType?: Int64Value | undefined;

  /**
   * 
   *
   * @generated from field: bilibili.app.distribution.v1.BoolValue enable_read_pasteboard = 3;
   */
  enableReadPasteboard?: BoolValue | undefined;

  /**
   * 
   *
   * @generated from field: bilibili.app.distribution.v1.BoolValue paste_auto_jump = 4;
   */
  pasteAutoJump?: BoolValue | undefined;

  /**
   * 
   *
   * @generated from field: bilibili.app.distribution.v1.BoolValue mini_screen_play_when_back = 5;
   */
  miniScreenPlayWhenBack?: BoolValue | undefined;

  /**
   * 
   *
   * @generated from field: bilibili.app.distribution.v1.BoolValue enable_resume_playing = 6;
   */
  enableResumePlaying?: BoolValue | undefined;

  /**
   * 
   *
   * @generated from field: bilibili.app.distribution.v1.BoolValue enable_wifi_auto_update = 7;
   */
  enableWifiAutoUpdate?: BoolValue | undefined;

  /**
   * 
   *
   * @generated from field: bilibili.app.distribution.v1.BoolValue enable_guide_screenshot_share = 8;
   */
  enableGuideScreenshotShare?: BoolValue | undefined;
};

/**
 * Describes the message bilibili.app.distribution.setting.other.OtherSettingsConfig.
 * Use `create(OtherSettingsConfigSchema)` to create a new message.
 */
export const OtherSettingsConfigSchema: GenMessage<OtherSettingsConfig> = /*@__PURE__*/
  messageDesc(file_bilibili_app_distribution_setting_other, 0);

