// @generated by protoc-gen-es v2.14.1 with parameter "target=ts"
// @generated from file bilibili/app/distribution/setting/pegasus.proto (package bilibili.app.distribution.setting.pegasus, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { BoolValue, Int64Value } from "../v1/distribution_pb";
import { file_bilibili_app_distribution_v1_distribution } from "../v1/distribution_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file bilibili/app/distribution/setting/pegasus.proto.
 */
export const file_bilibili_app_distribution_setting_pegasus: GenFile = /*@__PURE__*/
  fileDesc("Ci9iaWxpYmlsaS9hcHAvZGlzdHJpYnV0aW9uL3NldHRpbmcvcGVnYXN1cy5wcm90bxIpYmlsaWJpbGkuYXBwLmRpc3RyaWJ1dGlvbi5zZXR0aW5nLnBlZ2FzdXMiSAoNRmVlZE1vZGVWYWx1ZRI3CgV2YWx1ZRgBIAEoCzIoLmJpbGliaWxpLmFwcC5kaXN0cmlidXRpb24udjEuSW50NjRWYWx1ZSKnAgoPUGVnYXN1c0F1dG9QbGF5EjgKBnNpbmdsZRgBIAEoCzIoLmJpbGliaWxpLmFwcC5kaXN0cmlidXRpb24udjEuSW50NjRWYWx1ZRI4CgZkb3VibGUYAiABKAsyKC5iaWxpYmlsaS5hcHAuZGlzdHJpYnV0aW9uLnYxLkludDY0VmFsdWUSTwoec2luZ2xlX2FmZmVjdGVkX2J5X3NlcnZlcl9zaWRlGAMgASgLMicuYmlsaWJpbGkuYXBwLmRpc3RyaWJ1dGlvbi52MS5Cb29sVmFsdWUSTwoeZG91YmxlX2FmZmVjdGVkX2J5X3NlcnZlcl9zaWRlGAQgASgLMicuYmlsaWJpbGkuYXBwLmRpc3RyaWJ1dGlvbi52MS5Cb29sVmFsdWUilwEKElBlZ2FzdXNDb2x1bW5WYWx1ZRI3CgV2YWx1ZRgBIAEoCzIoLmJpbGliaWxpLmFwcC5kaXN0cmlidXRpb24udjEuSW50NjRWYWx1ZRJIChdhZmZlY3RlZF9ieV9zZXJ2ZXJfc2lkZRgCIAEoCzInLmJpbGliaWxpLmFwcC5kaXN0cmlidXRpb24udjEuQm9vbFZhbHVlIvsBChNQZWdhc3VzRGV2aWNlQ29uZmlnEk0KBmNvbHVtbhgBIAEoCzI9LmJpbGliaWxpLmFwcC5kaXN0cmlidXRpb24uc2V0dGluZy5wZWdhc3VzLlBlZ2FzdXNDb2x1bW5WYWx1ZRJGCgRtb2RlGAIgASgLMjguYmlsaWJpbGkuYXBwLmRpc3RyaWJ1dGlvbi5zZXR0aW5nLnBlZ2FzdXMuRmVlZE1vZGVWYWx1ZRJNCglhdXRvX3BsYXkYAyABKAsyOi5iaWxpYmlsaS5hcHAuZGlzdHJpYnV0aW9uLnNldHRpbmcucGVnYXN1cy5QZWdhc3VzQXV0b1BsYXliBnByb3RvMw", [file_bilibili_app_distribution_v1_distribution]);

/**
 * 
 *
 * @generated from message bilibili.app.distribution.setting.pegasus.FeedModeValue
 */
export type FeedModeValue = Message<"bilibili.app.distribution.setting.pegasus.FeedModeValue"> & {
  /**
   * 
   *
   * @generated from field: bilibili.app.distribution.v1.Int64Value value = 1;
   */
  value?: Int64Value | undefined;
};

/**
 * Describes the message bilibili.app.distribution.setting.pegasus.FeedModeValue.
 * Use `create(FeedModeValueSchema)` to create a new message.
 */
export const FeedModeValueSchema: GenMessage<FeedModeValue> = /*@__PURE__*/
  messageDesc(file_bilibili_app_distribution_setting_pegasus, 0);

/**
 * 
 *
 * @generated from message bilibili.app.distribution.setting.pegasus.PegasusAutoPlay
 */
export type PegasusAutoPlay = Message<"bilibili.app.distribution.setting.pegasus.PegasusAutoPlay"> & {
  /**
   * 
   *
   * @generated from field: bilibili.app.distribution.v1.Int64Value single = 1;
   */
  single?: Int64Value | undefined;

  /**
   * 
   *
   * @generated from field: bilibili.app.distribution.v1.Int64Value double = 2;
   */
  double?: Int64Value | undefined;

  /**
   * 
   *
   * @generated from field: bilibili.app.distribution.v1.BoolValue single_affected_by_server_side = 3;
   */
  singleAffectedByServerSide?: BoolValue | undefined;

  /**
   * 
   *
   * @generated from field: bilibili.app.distribution.v1.BoolValue double_affected_by_server_side = 4;
   */
  doubleAffectedByServerSide?: BoolValue | undefined;
};

/**
 * Describes the message bilibili.app.distribution.setting.pegasus.PegasusAutoPlay.
 * Use `create(PegasusAutoPlaySchema)` to create a new message.
 */
export const PegasusAutoPlaySchema: GenMessage<PegasusAutoPlay> = /*@__PURE__*/
  messageDesc(file_bilibili_app_distribution_setting_pegasus, 1);

/**
 * 
 *
 * @generated from message bilibili.app.distribution.setting.pegasus.PegasusColumnValue
 */
export type PegasusColumnValue = Message<"bilibili.app.distribution.setting.pegasus.PegasusColumnValue"> & {
  /**
   * 
   *
   * @generated from field: bilibili.app.distribution.v1.Int64Value value = 1;
   */
  value?: Int64Value | undefined;

  /**
   * 
   *
   * @generated from field: bilibili.app.distribution.v1.BoolValue affected_by_server_side = 2;
   */
  affectedByServerSide?: BoolValue | undefined;
};

/**
 * Describes the message bilibili.app.distribution.setting.pegasus.PegasusColumnValue.
 * Use `create(PegasusColumnValueSchema)` to create a new message.
 */
export const PegasusColumnValueSchema: GenMessage<PegasusColumnValue> = /*@__PURE__*/
  messageDesc(file_bilibili_app_distribution_setting_pegasus, 2);

/**
 * 
 *
 * @generated from message bilibili.app.distribution.setting.pegasus.PegasusDeviceConfig
 */
export type PegasusDeviceConfig = Message<"bilibili.app.distribution.setting.pegasus.PegasusDeviceConfig"> & {
  /**
   * 
   *
   * @generated from field: bilibili.app.distribution.setting.pegasus.PegasusColumnValue column = 1;
   */
  column?: PegasusColumnValue | undefined;

  /**
   * 
   *
   * @generated from field: bilibili.app.distribution.setting.pegasus.FeedModeValue mode = 2;
   */
  mode?: FeedModeValue | undefined;

  /**
   * 
   *
   * @generated from field: bilibili.app.distribution.setting.pegasus.PegasusAutoPlay auto_play = 3;
   */
  autoPlay?: PegasusAutoPlay | undefined;
};

/**
 * Describes the message bilibili.app.distribution.setting.pegasus.PegasusDeviceConfig.
 * Use `create(PegasusDeviceConfigSchema)` to create a new message.
 */
export const PegasusDeviceConfigSchema: GenMessage<PegasusDeviceConfig> = /*@__PURE__*/
  messageDesc(file_bilibili_app_distribution_setting_pegasus, 3);

