// @generated by protoc-gen-es v2.14.1 with parameter "target=ts"
// @generated from file bilibili/app/distribution/setting/privacy.proto (package bilibili.app.distribution.setting.privacy, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { BoolValue } from "../v1/distribution_pb";
import { file_bilibili_app_distribution_v1_distribution } from "../v1/distribution_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file bilibili/app/distribution/setting/privacy.proto.
 */
export const file_bilibili_app_distribution_setting_privacy: GenFile = /*@__PURE__*/
  fileDesc("Ci9iaWxpYmlsaS9hcHAvZGlzdHJpYnV0aW9uL3NldHRpbmcvcHJpdmFjeS5wcm90bxIpYmlsaWJpbGkuYXBwLmRpc3RyaWJ1dGlvbi5zZXR0aW5nLnByaXZhY3kiXwoYTWlkUHJpdmFjeVNldHRpbmdzQ29uZmlnEkMKEnJlY29tbWVuZF90b19rbm93bhgBIAEoCzInLmJpbGliaWxpLmFwcC5kaXN0cmlidXRpb24udjEuQm9vbFZhbHVlIpwBChVQcml2YWN5U2V0dGluZ3NDb25maWcSQwoSYWRfcmVjb21tYW5kX3N0b3JlGAEgASgLMicuYmlsaWJpbGkuYXBwLmRpc3RyaWJ1dGlvbi52MS5Cb29sVmFsdWUSPgoNc2Vuc29yX2FjY2VzcxgCIAEoCzInLmJpbGliaWxpLmFwcC5kaXN0cmlidXRpb24udjEuQm9vbFZhbHVlYgZwcm90bzM", [file_bilibili_app_distribution_v1_distribution]);

/**
 * 
 *
 * @generated from message bilibili.app.distribution.setting.privacy.MidPrivacySettingsConfig
 */
export type MidPrivacySettingsConfig = Message<"bilibili.app.distribution.setting.privacy.MidPrivacySettingsConfig"> & {
  /**
   * 
   *
   * @generated from field: bilibili.app.distribution.v1.BoolValue recommend_to_known = 1;
   */
  recommendToKnown?: BoolValue | undefined;
};

/**
 * Describes the message bilibili.app.distribution.setting.privacy.MidPrivacySettingsConfig.
 * Use `create(MidPrivacySettingsConfigSchema)` to create a new message.
 */
export const MidPrivacySettingsConfigSchema: GenMessage<MidPrivacySettingsConfig> = /*@__PURE__*/
  messageDesc(file_bilibili_app_distribution_setting_privacy, 0);

/**
 * 
 *
 * @generated from message bilibili.app.distribution.setting.privacy.PrivacySettingsConfig
 */
export type PrivacySettingsConfig = Message<"bilibili.app.distribution.setting.privacy.PrivacySettingsConfig"> & {
  /**
   * 
   *
   * @generated from field: bilibili.app.distribution.v1.BoolValue ad_recommand_store = 1;
   */
  adRecommandStore?: BoolValue | undefined;

  /**
   * 传感器权限
   *
   * @generated from field: bilibili.app.distribution.v1.BoolValue sensor_access = 2;
   */
  sensorAccess?: BoolValue | undefined;
};

/**
 * Describes the message bilibili.app.distribution.setting.privacy.PrivacySettingsConfig.
 * Use `create(PrivacySettingsConfigSchema)` to create a new message.
 */
export const PrivacySettingsConfigSchema: GenMessage<PrivacySettingsConfig> = /*@__PURE__*/
  messageDesc(file_bilibili_app_distribution_setting_privacy, 1);

