// @generated by protoc-gen-es v2.14.1 with parameter "target=ts"
// @generated from file bilibili/app/distribution/setting/search.proto (package bilibili.app.distribution.setting.search, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { BoolValue, Int64Value } from "../v1/distribution_pb";
import { file_bilibili_app_distribution_v1_distribution } from "../v1/distribution_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file bilibili/app/distribution/setting/search.proto.
 */
export const file_bilibili_app_distribution_setting_search: GenFile = /*@__PURE__*/
  fileDesc("Ci5iaWxpYmlsaS9hcHAvZGlzdHJpYnV0aW9uL3NldHRpbmcvc2VhcmNoLnByb3RvEihiaWxpYmlsaS5hcHAuZGlzdHJpYnV0aW9uLnNldHRpbmcuc2VhcmNoIpMBCg5TZWFyY2hBdXRvUGxheRI3CgV2YWx1ZRgBIAEoCzIoLmJpbGliaWxpLmFwcC5kaXN0cmlidXRpb24udjEuSW50NjRWYWx1ZRJIChdhZmZlY3RlZF9ieV9zZXJ2ZXJfc2lkZRgCIAEoCzInLmJpbGliaWxpLmFwcC5kaXN0cmlidXRpb24udjEuQm9vbFZhbHVlImEKElNlYXJjaERldmljZUNvbmZpZxJLCglhdXRvX3BsYXkYASABKAsyOC5iaWxpYmlsaS5hcHAuZGlzdHJpYnV0aW9uLnNldHRpbmcuc2VhcmNoLlNlYXJjaEF1dG9QbGF5YgZwcm90bzM", [file_bilibili_app_distribution_v1_distribution]);

/**
 * 
 *
 * @generated from message bilibili.app.distribution.setting.search.SearchAutoPlay
 */
export type SearchAutoPlay = Message<"bilibili.app.distribution.setting.search.SearchAutoPlay"> & {
  /**
   * 
   *
   * @generated from field: bilibili.app.distribution.v1.Int64Value value = 1;
   */
  value?: Int64Value | undefined;

  /**
   * 
   *
   * @generated from field: bilibili.app.distribution.v1.BoolValue affected_by_server_side = 2;
   */
  affectedByServerSide?: BoolValue | undefined;
};

/**
 * Describes the message bilibili.app.distribution.setting.search.SearchAutoPlay.
 * Use `create(SearchAutoPlaySchema)` to create a new message.
 */
export const SearchAutoPlaySchema: GenMessage<SearchAutoPlay> = /*@__PURE__*/
  messageDesc(file_bilibili_app_distribution_setting_search, 0);

/**
 * 
 *
 * @generated from message bilibili.app.distribution.setting.search.SearchDeviceConfig
 */
export type SearchDeviceConfig = Message<"bilibili.app.distribution.setting.search.SearchDeviceConfig"> & {
  /**
   * 
   *
   * @generated from field: bilibili.app.distribution.setting.search.SearchAutoPlay auto_play = 1;
   */
  autoPlay?: SearchAutoPlay | undefined;
};

/**
 * Describes the message bilibili.app.distribution.setting.search.SearchDeviceConfig.
 * Use `create(SearchDeviceConfigSchema)` to create a new message.
 */
export const SearchDeviceConfigSchema: GenMessage<SearchDeviceConfig> = /*@__PURE__*/
  messageDesc(file_bilibili_app_distribution_setting_search, 1);

