name: APM Android dev Build
on:
  schedule:
    - cron: '0 0 * * 1'
  push:
    branches:
      - 'dev'
      - 'dev-newarch'
  workflow_dispatch:
jobs:
  checkLastCommit:
    uses: ./.github/workflows/reuse-check-last-commit.yml      
  build:
    name: Build
    runs-on: ubuntu-latest
    needs: checkLastCommit
    if: ${{ needs.checkLastCommit.outputs.is_new_commit }}
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Android Build Setup
        uses: ./.github/composite-actions/android-runner-setup

      - name: React Native Build Setup
        id: rnsetup
        uses: ./.github/composite-actions/RN-setup
        with:
          env: ${{ secrets.ENV_FILE }}
          sentry: ${{ secrets.SENTRY_PROPERTIES }}

      - name: python fixHTTP
        run: |
          python ./scripts/dev_cleartext.py
          python ./scripts/release_bump.py --dev

      - name: Build Android
        uses: ./.github/composite-actions/build-apk
        with:
          signpwd: ${{ secrets.RELEASE_SIGN_PWD }}
          signkey: ${{ secrets.SIGNED_KEY_BASE64 }}

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.GIT_BRANCH }}-build-${{ steps.rnsetup.outputs.date }}
          files: android/app/build/outputs/apk/release/app-arm64-v8a-release.apk
          prerelease: true
          target_commitish: ${{ env.GIT_BRANCH }}
