name: APM Build Benchmark
on:
  workflow_dispatch:
jobs:
  build-apk-ubuntu:
    name: android-ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Android Build Setup
        uses: ./.github/composite-actions/android-runner-setup

      - name: React Native Build Setup
        uses: ./.github/composite-actions/RN-setup
        with:
          env: ${{ secrets.ENV_FILE }}
          sentry: ${{ secrets.SENTRY_PROPERTIES }}

      - name: Build Android
        uses: ./.github/composite-actions/build-apk
        with:
          signpwd: ${{ secrets.RELEASE_SIGN_PWD }}
          signkey: ${{ secrets.SIGNED_KEY_BASE64 }}
            build-apk-ubuntu:

  build-apk-windows:
    name: android-windows
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Android Build Setup
        uses: ./.github/composite-actions/android-runner-setup

      - name: React Native Build Setup
        uses: ./.github/composite-actions/RN-setup
        with:
          env: ${{ secrets.ENV_FILE }}
          sentry: ${{ secrets.SENTRY_PROPERTIES }}

      - name: Build Android
        uses: ./.github/composite-actions/build-apk
        with:
          signpwd: ${{ secrets.RELEASE_SIGN_PWD }}
          signkey: ${{ secrets.SIGNED_KEY_BASE64 }}