name: APM Build Benchmark
on:
  workflow_dispatch:
jobs:
  build-apk-ubuntu:
    name: android-ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Android Build Setup
        uses: ./.github/composite-actions/android-runner-setup

      - name: React Native Build Setup
        uses: ./.github/composite-actions/RN-setup
        with:
          env: ${{ secrets.ENV_FILE }}
          sentry: ${{ secrets.SENTRY_PROPERTIES }}

      - name: Build Android
        uses: ./.github/composite-actions/build-apk
        with:
          signpwd: ${{ secrets.RELEASE_SIGN_PWD }}
          signkey: ${{ secrets.SIGNED_KEY_BASE64 }}

  build-apk-windows:
    name: android-windows
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Android Build Setup
        uses: ./.github/composite-actions/android-runner-setup

      - name: enable corepack
        run: |
          corepack enable
          yarn set version berry

      - name: enable corepack
        run: |
          corepack enable
          yarn set version berry
        shell: cmd

      - name: React Native Build Setup
        uses: ./.github/composite-actions/RN-setup
        with:
          env: ${{ secrets.ENV_FILE }}
          sentry: ${{ secrets.SENTRY_PROPERTIES }}

      - name: Build Android
        uses: ./.github/composite-actions/build-apk
        with:
          signpwd: ${{ secrets.RELEASE_SIGN_PWD }}
          signkey: ${{ secrets.SIGNED_KEY_BASE64 }}

  build-apk-ubuntu-arm:
    name: android-ubuntu-arm
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Android Build Setup
        uses: ./.github/composite-actions/android-runner-setup

      - name: React Native Build Setup
        uses: ./.github/composite-actions/RN-setup
        with:
          env: ${{ secrets.ENV_FILE }}
          sentry: ${{ secrets.SENTRY_PROPERTIES }}

      - name: Build Android
        uses: ./.github/composite-actions/build-apk
        with:
          signpwd: ${{ secrets.RELEASE_SIGN_PWD }}
          signkey: ${{ secrets.SIGNED_KEY_BASE64 }}

  buildIPA:
    runs-on: macos-latest
    name: build IPA
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: React Native Build Setup
        uses: ./.github/composite-actions/RN-setup  
        with:
          env: ${{ secrets.ENV_FILE }}
          sentry: ${{ secrets.SENTRY_PROPERTIES }}
    
      - name: pod install
        run: |
          sudo xcode-select -switch /Applications/Xcode_26.0.app
          yarn ios:build
      
      - name: Build IPA
        run: |
          cd ios  && xcodebuild -downloadPlatform iOS && xcodebuild -scheme APM -workspace example.xcworkspace -destination generic/platform=iOS -configuration Release clean archive -archivePath "build/APM.xcarchive" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO

