name: APM OTA
on:
  workflow_dispatch:
  push:
    branches:
      - 'dev'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get branch name
        run: |
          # Short name for current branch. For PRs, use target branch (base ref)
          GIT_BRANCH=${GITHUB_BASE_REF:-${GITHUB_REF#refs/heads/}}
          echo "GIT_BRANCH=$GIT_BRANCH" >> $GITHUB_ENV

      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: set up JDK 18
        uses: actions/setup-java@v4
        with:
          java-version: 18
          distribution: temurin

      - name: enable corepack
        run: corepack enable

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'yarn'

      - name: 'Create env file'
        env:
          ENV_FILE: ${{ secrets.ENV_FILE }}
          SENTRY_PROPERTIES: ${{ secrets.SENTRY_PROPERTIES }}
        run: |
          echo "$ENV_FILE" > .env
          echo "$SENTRY_PROPERTIES" > ./android/sentry.properties
          echo "TRACKING=true" >> .env
          # enables OTA hot update
          python scripts/hashyarnlock.py

      - name: alias yarn.cmd to yarn
        run: alias yarn.cmd="yarn"

      - name: Add Build Sign Keys
        run: |
          git submodule update --init --recursive
          echo "${{ secrets.RELEASE_SIGN_PWD }}" >> ./android/gradle.properties

      - name: Build Sign jks
        id: write_file
        uses: timheuer/base64-to-file@v1.2
        with:
          fileName: 'noxupload.jks'
          fileDir: './android/app'
          encodedString: ${{ secrets.SIGNED_KEY_BASE64 }}

      - name: Install dependencies
        run: yarn install; yarn build

      - name: python fixHTTP
        run: |
          python ./scripts/fixHTTP.py
          python ./scripts/dev_cleartext.py
          python ./scripts/release_bump.py --dev

      - name: clean generated builds
        run: rm -rf android/app/build/generated/

      - name: Push Build to Github
        run: |
          yarn ota
          cd bundles
          git init
          git branch -m OTA
          git remote add origin https://${{ secrets.GHTOKEN }}@github.com/lovegaoshi/azusa-player-mobile.git
          git add .
          git config --global user.email "love@gaoshi.com"
          git config --global user.name "gaoshi"
          git commit -m 'release'
          git push --set-upstream origin OTA --force
