name: APM OTA
on:
  workflow_dispatch:
  push:
    branches:
      - 'dev'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: React Native Build Setup
        uses: ./.github/composite-actions/RN-setup  
    
      - name: 'Create env file'
        run: |
          echo "TRACKING=true" >> .env
          # enables OTA hot update
          python scripts/hashyarnlock.py

      - name: Add Build Sign Keys
        run: |
          echo "${{ secrets.RELEASE_SIGN_PWD }}" >> ./android/gradle.properties

      - name: Build Sign jks
        id: write_file
        uses: timheuer/base64-to-file@v1.2
        with:
          fileName: 'noxupload.jks'
          fileDir: './android/app'
          encodedString: ${{ secrets.SIGNED_KEY_BASE64 }}

      - name: python fixHTTP
        run: |
          python ./scripts/dev_cleartext.py
          python ./scripts/release_bump.py --dev

      - name: clean generated builds
        run: rm -rf android/app/build/generated/

      - name: Push Build to Github
        run: |
          yarn ota
          cd bundles
          git init
          git branch -m OTA
          git remote add origin https://${{ secrets.GHTOKEN }}@github.com/lovegaoshi/azusa-player-mobile.git
          git add .
          git config --global user.email "love@gaoshi.com"
          git config --global user.name "gaoshi"
          git commit -m 'release'
          git push --set-upstream origin OTA --force
