name: APM Play Store Release
on:
  workflow_dispatch:
jobs:
  buildAAB:
    runs-on: ubuntu-latest
    name: build AAB
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Android Build Setup
        uses: ./.github/composite-actions/android-runner-setup

      - name: python version_bump.py
        run: |
          python ./scripts/version_bump.py

      - name: commit
        run: |
          git config --global user.email 106490582+lovegaoshi@users.noreply.github.com
          git config --global user.name lovegaoshi
          git commit -m "build: release version bump" -a

      - name: React Native Build Setup
        uses: ./.github/composite-actions/RN-setup  
        with:
          env: ${{ secrets.ENV_FILE }}
          sentry: ${{ secrets.SENTRY_PROPERTIES }}

      - name: 'Create env file'
        run: |
          echo "APPSTORE=true" >> .env
          echo "TRACKING=true" >> .env
          # enables OTA hot update
          python scripts/hashyarnlock.py

      - name: Build Android
        uses: ./.github/composite-actions/build-apk
        with:
          signpwd: ${{ secrets.RELEASE_SIGN_PWD }}
          signkey: ${{ secrets.SIGNED_KEY_BASE64 }}
          buildtype: bundleRelease

      - name: Push changes to master
        uses: ad-m/github-push-action@master

      - uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.GOOGLE_PLAY_SERVICE_ACCOUNT_JSON }}
          packageName: com.noxplay.noxplayer
          releaseFiles: android/app/build/outputs/bundle/release/app-release.aab
          track: internal
          # changesNotSentForReview: true
