// @generated by protoc-gen-es v2.14.1 with parameter "target=ts"
// @generated from file bilibili/broadcast/v2/laser.proto (package bilibili.broadcast.v2, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { EmptySchema } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_empty } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file bilibili/broadcast/v2/laser.proto.
 */
export const file_bilibili_broadcast_v2_laser: GenFile = /*@__PURE__*/
  fileDesc("CiFiaWxpYmlsaS9icm9hZGNhc3QvdjIvbGFzZXIucHJvdG8SFWJpbGliaWxpLmJyb2FkY2FzdC52MiJACg5MYXNlckV2ZW50UmVzcBIOCgZ0YXNraWQYASABKAMSDgoGYWN0aW9uGAIgASgJEg4KBnBhcmFtcxgDIAEoCTJWCgVMYXNlchJNCgpXYXRjaEV2ZW50EhYuZ29vZ2xlLnByb3RvYnVmLkVtcHR5GiUuYmlsaWJpbGkuYnJvYWRjYXN0LnYyLkxhc2VyRXZlbnRSZXNwMAFiBnByb3RvMw", [file_google_protobuf_empty]);

/**
 * 服务端下发Laser事件
 *
 * @generated from message bilibili.broadcast.v2.LaserEventResp
 */
export type LaserEventResp = Message<"bilibili.broadcast.v2.LaserEventResp"> & {
  /**
   * 任务id
   *
   * @generated from field: int64 taskid = 1;
   */
  taskid: bigint;

  /**
   * 指令名
   *
   * @generated from field: string action = 2;
   */
  action: string;

  /**
   * 指令参数json字符串
   *
   * @generated from field: string params = 3;
   */
  params: string;
};

/**
 * Describes the message bilibili.broadcast.v2.LaserEventResp.
 * Use `create(LaserEventRespSchema)` to create a new message.
 */
export const LaserEventRespSchema: GenMessage<LaserEventResp> = /*@__PURE__*/
  messageDesc(file_bilibili_broadcast_v2_laser, 0);

/**
 * Laser
 *
 * @generated from service bilibili.broadcast.v2.Laser
 */
export const Laser: GenService<{
  /**
   * 监听Laser事件
   *
   * @generated from rpc bilibili.broadcast.v2.Laser.WatchEvent
   */
  watchEvent: {
    methodKind: "server_streaming";
    input: typeof EmptySchema;
    output: typeof LaserEventRespSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_bilibili_broadcast_v2_laser, 0);

